# Generated from cmd/vif/usage.go by TestGeneratedFilesAreTheHelpTable; do not edit.
complete -c vif -f
complete -c vif -o host -x -d 'Play at once and open the game to participants, e.g. :7777 or ws://:7777'
complete -c vif -o serve -x -d 'Bind a headless session with no local cursor, e.g. :7777 or ws://:7777'
complete -c vif -o join -x -d 'Join a session at [tcp://|vif://]host:port[/name] or a ws(s):// URL, or a new one an http(s):// site creates; tcp when no scheme is given'
complete -c vif -o name -x -d 'Name this host answers to, so one address can serve several sessions'
complete -c vif -o players -x -d 'Roster ceiling including self, 2..16; unset holds the whole roster; with a -join site, the one requested'
complete -c vif -o bots -x -d 'Seat n bots playing graph (default default) in this run\'s session; a solo run hosts them on loopback'
complete -c vif -o authority -x -a 'host migrate' -d 'Where authorship goes when the authoring participant leaves; default host with -serve, migrate otherwise'
complete -c vif -o slow-window -x -d 'Window a participant\'s lateness is judged over; host only, 0 never evicts (default 20s)'
complete -c vif -o slow-late -x -d 'Evict at this many late epochs per second over the window; 0 ignores lateness (default 5)'
complete -c vif -o slow-bytes -x -d '...and at least this many bytes per second on its link; 0 ignores throughput (default 8192)'
complete -c vif -o listen -x -d 'Address this participant is dialled back on; -join only, default the host\'s port then an ephemeral one'
complete -c vif -o no-advertise -d 'Keep this participant\'s address out of the session; -join only, and it is never elected'
complete -c vif -o size -x -d 'Terminal-equivalent size for a run that has no terminal'
complete -c vif -o probe -x -d 'Health and metrics endpoint; -serve only'
complete -c vif -o first-join -x -d 'Exit if no guest connects within this; -serve only, 0 waits forever'
complete -c vif -o empty -x -d 'Exit this long after the last guest leaves; -serve only, 0 keeps the session'
complete -c vif -o drain -x -d 'How long a termination signal waits for an empty roster; -serve only, 0 exits at once'
complete -c vif -o d -o config-embedded -d 'Use the embedded scenario and content, ignoring -s and -f'
complete -c vif -o config-dir -x -a '(__fish_complete_directories)' -d 'Configuration root holding scenario/ input/ audio/ content/ image/ bot/'
complete -c vif -o s -o config-scenario -r -F -d 'Installed scenario name, scenario.toml, or a scenario directory'
complete -c vif -o f -o config-content -r -F -d 'Content directory, or a single content file'
complete -c vif -o k -o config-keymap -r -F -d 'Keymap TOML'
complete -c vif -o config-music -r -F -d 'Music pattern override TOML'
complete -c vif -o config-sounds -r -F -d 'Sound definition override TOML'
complete -c vif -o color -x -a 'auto 256 true' -d 'Colour depth; auto detects the terminal'
complete -c vif -o mute -d 'Start muted, which is the default; -mute=false starts with sound'
complete -c vif -o ab -o audio-backend -x -d 'Force an audio backend instead of detecting one'
complete -c vif -o seed -x -d 'Root RNG seed; 0 draws one and logs it'
complete -c vif -o speed -x -d 'Simulation rate 1/8 1/4 1/2 1 2 4 8; with -script or -bot also "max" for no wall pacing'
complete -c vif -o script -r -F -d 'Run an authored deterministic TOML tick script'
complete -c vif -o bot -r -F -d 'Play this instance\'s own seat with a bot graph instead of the terminal'
complete -c vif -o watch -d 'Present a -script or -bot run on this terminal instead of running it headlessly'
complete -c vif -o replay -r -F -d 'Replay a recorded journal instead of playing'
complete -c vif -o check -d 'Validate the resolved scenario, keymap, audio and content, then exit'
complete -c vif -o schema -d 'Print the FSM schema as JSON, then exit'
complete -c vif -o l -o log -d 'Enable logging; DIR overrides $XDG_STATE_HOME/vif/log'
complete -c vif -o lv -o log-level -x -d 'trace, debug, info, warn or error; implies -l'
complete -c vif -o ls -o log-scope -x -d 'Which subsystems log; see Scopes below; implies -l'
complete -c vif -o lt -o log-stat -x -d 'Status snapshot period in game ticks, 0 disables; implies -l'
complete -c vif -o lr -o log-recorder -x -d 'Flight recorder depth in game ticks, 0 disables; implies -l'
complete -c vif -o log-session-id -x -d 'Attach a session ID to every application log record; implies -l'
complete -c vif -o log-stdout -d 'Write the log to stdout as JSON instead of to a file; implies -l'
complete -c vif -o j -o journal -d 'Record a replay journal; DIR overrides $XDG_STATE_HOME/vif/journal'
complete -c vif -o mw -o music-wav -d 'Record the music alone, as it plays, to a WAV file; DIR overrides $XDG_STATE_HOME/vif/music'
complete -c vif -o dev -d 'Capture runtime stderr to a file; on by default for -race builds'
complete -c vif -o h -o help -d 'Print this and exit'
complete -c vif -o version -d 'Print the module version and commit a package should report'
