# Root configuration with region definitions

[regions.main]
file = "main.toml"
enabled_systems = ["glyph"]

[regions.quasar]
file = "quasar.toml"
enabled_systems = ["glyph"]

[regions.storm]
file = "storm.toml"
enabled_systems = ["glyph"]

[regions.kraken]
file = "kraken.toml"
enabled_systems = ["glyph", "nugget"]

[regions.monitor]
initial = "MonitorBoot"
file = "monitor.toml"
background = true

[regions.tower]
file = "tower.toml"
disabled_systems = ["glyph"]

#[states.Root]
