// Code generated by gen-manifest; DO NOT EDIT.

//go:build !vif_headless

package manifest

import (
	"github.com/lixenwraith/vif/internal/engine"
	"github.com/lixenwraith/vif/internal/render"
	"github.com/lixenwraith/vif/internal/render/renderer"
)

// BuildRenderers constructs every active renderer paired with its name and priority.
func BuildRenderers(ctx *engine.GameContext) []render.Registration {
	return []render.Registration{
		{Name: "ping", Renderer: renderer.NewPingRenderer(ctx), Priority: render.PriorityPing},
		{Name: "chargeline", Renderer: renderer.NewChargeLineRenderer(ctx), Priority: render.PriorityChargeLine},
		{Name: "wall", Renderer: renderer.NewWallRenderer(ctx), Priority: render.PriorityWall},
		{Name: "glyph", Renderer: renderer.NewGlyphRenderer(ctx), Priority: render.PriorityGlyph},
		{Name: "sigil", Renderer: renderer.NewSigilRenderer(ctx), Priority: render.PrioritySigil},
		{Name: "gold", Renderer: renderer.NewGoldRenderer(ctx), Priority: render.PriorityGold},
		{Name: "healthbar", Renderer: renderer.NewHealthBarRenderer(ctx), Priority: render.PriorityHealthBar},
		{Name: "pylon", Renderer: renderer.NewPylonRenderer(ctx), Priority: render.PriorityPylon},
		{Name: "tower", Renderer: renderer.NewTowerRenderer(ctx), Priority: render.PriorityTower},
		{Name: "eye", Renderer: renderer.NewEyeRenderer(ctx), Priority: render.PriorityEye},
		{Name: "snake", Renderer: renderer.NewSnakeRenderer(ctx), Priority: render.PrioritySnake},
		{Name: "drain", Renderer: renderer.NewDrainRenderer(ctx), Priority: render.PriorityDrain},
		{Name: "quasar", Renderer: renderer.NewQuasarRenderer(ctx), Priority: render.PriorityQuasar},
		{Name: "swarm", Renderer: renderer.NewSwarmRenderer(ctx), Priority: render.PrioritySwarm},
		{Name: "storm", Renderer: renderer.NewStormRenderer(ctx), Priority: render.PriorityStorm},
		{Name: "kraken", Renderer: renderer.NewKrakenRenderer(ctx), Priority: render.PriorityKraken},
		{Name: "cleaner", Renderer: renderer.NewCleanerRenderer(ctx), Priority: render.PriorityCleaner},
		{Name: "materialize", Renderer: renderer.NewMaterializeRenderer(ctx), Priority: render.PriorityMaterialize},
		{Name: "teleportline", Renderer: renderer.NewTeleportLineRenderer(ctx), Priority: render.PriorityTeleportLine},
		{Name: "shield", Renderer: renderer.NewShieldRenderer(ctx), Priority: render.PriorityShield},
		{Name: "ember", Renderer: renderer.NewEmberRenderer(ctx), Priority: render.PriorityEmber},
		{Name: "orb", Renderer: renderer.NewOrbRenderer(ctx), Priority: render.PriorityOrb},
		{Name: "lightning", Renderer: renderer.NewLightningRenderer(ctx), Priority: render.PriorityLightning},
		{Name: "missile", Renderer: renderer.NewMissileRenderer(ctx), Priority: render.PriorityMissile},
		{Name: "pulse", Renderer: renderer.NewPulseRenderer(ctx), Priority: render.PriorityPulse},
		{Name: "ray", Renderer: renderer.NewRayRenderer(ctx), Priority: render.PriorityRay},
		{Name: "bullet", Renderer: renderer.NewBulletRenderer(ctx), Priority: render.PriorityBullet},
		{Name: "flash", Renderer: renderer.NewFlashRenderer(ctx), Priority: render.PriorityFlash},
		{Name: "fadeout", Renderer: renderer.NewFadeoutRenderer(ctx), Priority: render.PriorityFadeout},
		{Name: "explosion", Renderer: renderer.NewExplosionRenderer(ctx), Priority: render.PriorityExplosion},
		{Name: "spirit", Renderer: renderer.NewSpiritRenderer(ctx), Priority: render.PrioritySpirit},
		{Name: "splash", Renderer: renderer.NewSplashRenderer(ctx), Priority: render.PrioritySplash},
		{Name: "marker", Renderer: renderer.NewMarkerRenderer(ctx), Priority: render.PriorityMarker},
		{Name: "grayout", Renderer: renderer.NewGrayoutRenderer(ctx), Priority: render.PriorityGrayout},
		{Name: "strobe", Renderer: renderer.NewStrobeRenderer(ctx), Priority: render.PriorityStrobe},
		{Name: "dim", Renderer: renderer.NewDimRenderer(ctx), Priority: render.PriorityDim},
		{Name: "heat", Renderer: renderer.NewHeatRenderer(ctx), Priority: render.PriorityHeat},
		{Name: "indicator", Renderer: renderer.NewIndicatorRenderer(ctx), Priority: render.PriorityIndicator},
		{Name: "statusbar", Renderer: renderer.NewStatusBarRenderer(ctx), Priority: render.PriorityStatusBar},
		{Name: "peer_cursor", Renderer: renderer.NewPeerCursorRenderer(ctx), Priority: render.PriorityPeerCursor},
		{Name: "cursor", Renderer: renderer.NewCursorRenderer(ctx), Priority: render.PriorityCursor},
		{Name: "flowfield", Renderer: renderer.NewFlowFieldDebugRenderer(ctx), Priority: render.PriorityFlowField},
		{Name: "pinned_state", Renderer: renderer.NewPinnedStatsRenderer(ctx), Priority: render.PriorityPinnedState},
		{Name: "overlay", Renderer: renderer.NewOverlayRenderer(ctx), Priority: render.PriorityOverlay},
	}
}
