// Code generated by gen-manifest; DO NOT EDIT.

package input

import "fmt"

func (i IntentType) String() string {
	switch i {
	case IntentNone:
		return "IntentNone"
	case IntentQuit:
		return "IntentQuit"
	case IntentEscape:
		return "IntentEscape"
	case IntentToggleAudioCycle:
		return "IntentToggleAudioCycle"
	case IntentMotion:
		return "IntentMotion"
	case IntentCharMotion:
		return "IntentCharMotion"
	case IntentOperatorMotion:
		return "IntentOperatorMotion"
	case IntentOperatorLine:
		return "IntentOperatorLine"
	case IntentOperatorCharMotion:
		return "IntentOperatorCharMotion"
	case IntentSpecial:
		return "IntentSpecial"
	case IntentNuggetJump:
		return "IntentNuggetJump"
	case IntentGoldJump:
		return "IntentGoldJump"
	case IntentFireMain:
		return "IntentFireMain"
	case IntentFireSpecial:
		return "IntentFireSpecial"
	case IntentMotionMarkerShow:
		return "IntentMotionMarkerShow"
	case IntentMotionMarkerJump:
		return "IntentMotionMarkerJump"
	case IntentMacroRecordStart:
		return "IntentMacroRecordStart"
	case IntentMacroRecordStop:
		return "IntentMacroRecordStop"
	case IntentMacroPlay:
		return "IntentMacroPlay"
	case IntentMacroPlayInfinite:
		return "IntentMacroPlayInfinite"
	case IntentMacroPlayAll:
		return "IntentMacroPlayAll"
	case IntentMacroStopOne:
		return "IntentMacroStopOne"
	case IntentMacroStopAll:
		return "IntentMacroStopAll"
	case IntentMacroRecordToggle:
		return "IntentMacroRecordToggle"
	case IntentModeSwitch:
		return "IntentModeSwitch"
	case IntentToggleAutoFire:
		return "IntentToggleAutoFire"
	case IntentTextChar:
		return "IntentTextChar"
	case IntentTextBackspace:
		return "IntentTextBackspace"
	case IntentTextConfirm:
		return "IntentTextConfirm"
	case IntentTextNav:
		return "IntentTextNav"
	case IntentInsertDeleteCurrent:
		return "IntentInsertDeleteCurrent"
	case IntentInsertDeleteForward:
		return "IntentInsertDeleteForward"
	case IntentInsertDeleteBack:
		return "IntentInsertDeleteBack"
	case IntentUndo:
		return "IntentUndo"
	case IntentOverlayScroll:
		return "IntentOverlayScroll"
	case IntentOverlayActivate:
		return "IntentOverlayActivate"
	case IntentOverlayClose:
		return "IntentOverlayClose"
	case IntentOverlayPageUp:
		return "IntentOverlayPageUp"
	case IntentOverlayPageDown:
		return "IntentOverlayPageDown"
	case IntentOverlayFilter:
		return "IntentOverlayFilter"
	case IntentMouseLeftDown:
		return "IntentMouseLeftDown"
	case IntentMouseLeftUp:
		return "IntentMouseLeftUp"
	case IntentMouseRightDown:
		return "IntentMouseRightDown"
	case IntentMouseRightUp:
		return "IntentMouseRightUp"
	case IntentMouseDrag:
		return "IntentMouseDrag"
	case IntentMouseWheelMove:
		return "IntentMouseWheelMove"
	case IntentMouseMove:
		return "IntentMouseMove"
	case IntentConfigMenu:
		return "IntentConfigMenu"
	default:
		return fmt.Sprintf("IntentType(%d)", i)
	}
}

func (i ModeTarget) String() string {
	switch i {
	case ModeTargetNone:
		return "ModeTargetNone"
	case ModeTargetInsert:
		return "ModeTargetInsert"
	case ModeTargetSearch:
		return "ModeTargetSearch"
	case ModeTargetCommand:
		return "ModeTargetCommand"
	case ModeTargetNormal:
		return "ModeTargetNormal"
	case ModeTargetVisual:
		return "ModeTargetVisual"
	default:
		return fmt.Sprintf("ModeTarget(%d)", i)
	}
}

func (i MotionOp) String() string {
	switch i {
	case MotionNone:
		return "MotionNone"
	case MotionLeft:
		return "MotionLeft"
	case MotionRight:
		return "MotionRight"
	case MotionUp:
		return "MotionUp"
	case MotionDown:
		return "MotionDown"
	case MotionWordForward:
		return "MotionWordForward"
	case MotionWORDForward:
		return "MotionWORDForward"
	case MotionWordBack:
		return "MotionWordBack"
	case MotionWORDBack:
		return "MotionWORDBack"
	case MotionWordEnd:
		return "MotionWordEnd"
	case MotionWORDEnd:
		return "MotionWORDEnd"
	case MotionLineStart:
		return "MotionLineStart"
	case MotionLineEnd:
		return "MotionLineEnd"
	case MotionFirstNonWS:
		return "MotionFirstNonWS"
	case MotionScreenVerticalMid:
		return "MotionScreenVerticalMid"
	case MotionScreenHorizontalMid:
		return "MotionScreenHorizontalMid"
	case MotionScreenTop:
		return "MotionScreenTop"
	case MotionScreenBottom:
		return "MotionScreenBottom"
	case MotionParaBack:
		return "MotionParaBack"
	case MotionParaForward:
		return "MotionParaForward"
	case MotionMatchBracket:
		return "MotionMatchBracket"
	case MotionOrigin:
		return "MotionOrigin"
	case MotionEnd:
		return "MotionEnd"
	case MotionCenter:
		return "MotionCenter"
	case MotionFindForward:
		return "MotionFindForward"
	case MotionFindBack:
		return "MotionFindBack"
	case MotionTillForward:
		return "MotionTillForward"
	case MotionTillBack:
		return "MotionTillBack"
	case MotionHalfPageLeft:
		return "MotionHalfPageLeft"
	case MotionHalfPageRight:
		return "MotionHalfPageRight"
	case MotionHalfPageUp:
		return "MotionHalfPageUp"
	case MotionHalfPageDown:
		return "MotionHalfPageDown"
	case MotionColumnUp:
		return "MotionColumnUp"
	case MotionColumnDown:
		return "MotionColumnDown"
	case MotionColoredGlyphRight:
		return "MotionColoredGlyphRight"
	case MotionColoredGlyphLeft:
		return "MotionColoredGlyphLeft"
	case MotionColoredGlyphUp:
		return "MotionColoredGlyphUp"
	case MotionColoredGlyphDown:
		return "MotionColoredGlyphDown"
	default:
		return fmt.Sprintf("MotionOp(%d)", i)
	}
}

func (i OperatorOp) String() string {
	switch i {
	case OperatorNone:
		return "OperatorNone"
	case OperatorDelete:
		return "OperatorDelete"
	default:
		return fmt.Sprintf("OperatorOp(%d)", i)
	}
}

func (i ScrollDir) String() string {
	switch i {
	case ScrollNone:
		return "ScrollNone"
	case ScrollUp:
		return "ScrollUp"
	case ScrollDown:
		return "ScrollDown"
	default:
		return fmt.Sprintf("ScrollDir(%d)", i)
	}
}

func (i SpecialOp) String() string {
	switch i {
	case SpecialNone:
		return "SpecialNone"
	case SpecialDeleteChar:
		return "SpecialDeleteChar"
	case SpecialDeleteToEnd:
		return "SpecialDeleteToEnd"
	case SpecialSearchNext:
		return "SpecialSearchNext"
	case SpecialSearchPrev:
		return "SpecialSearchPrev"
	case SpecialRepeatFind:
		return "SpecialRepeatFind"
	case SpecialRepeatFindRev:
		return "SpecialRepeatFindRev"
	default:
		return fmt.Sprintf("SpecialOp(%d)", i)
	}
}
