// Code generated by gen-manifest; DO NOT EDIT.

package engine

import (
	"github.com/lixenwraith/vif/internal/component"
	"github.com/lixenwraith/vif/internal/core"
)

// Component ID Bitmasks Mapping for Engine-Level Entity Signatures
// Used for O(1) destruction skipping and future fast queries
const (
	GlyphBit uint64 = 1 << iota
	SigilBit
	NuggetBit
	CursorBit
	ProtectionBit
	KineticBit
	WallBit
	LootBit
	GatewayBit
	EnergyBit
	HeatBit
	ShieldBit
	BoostBit
	WeaponBit
	OrbBit
	PingBit
	CursorViewBit
	ParticleBit
	CleanerBit
	DustBit
	NavigationBit
	CombatBit
	GenotypeBit
	LightningBit
	MissileBit
	MountBit
	BeamBit
	SpiritBit
	MaterializeBit
	TargetBit
	TargetAnchorBit
	DrainBit
	QuasarBit
	SwarmBit
	StormBit
	StormCircleBit
	BulletBit
	PylonBit
	SnakeBit
	SnakeHeadBit
	SnakeBodyBit
	SnakeMemberBit
	EyeBit
	TowerBit
	KrakenBit
	HeaderBit
	MemberBit
	FlashBit
	FadeoutBit
	SplashBit
	MarkerBit
	DeathBit
	TimerBit
	PositionBit // Special index designated for spatial grid presence
)

// Component provides typed component store pointers
// Embedded in World, initialized once at world creation
type Component struct {
	Glyph        *Store[component.GlyphComponent]
	Sigil        *Store[component.SigilComponent]
	Nugget       *Store[component.NuggetComponent]
	Cursor       *Store[component.CursorComponent]
	Protection   *Store[component.ProtectionComponent]
	Kinetic      *Store[component.KineticComponent]
	Wall         *Store[component.WallComponent]
	Loot         *Store[component.LootComponent]
	Gateway      *Store[component.GatewayComponent]
	Energy       *Store[component.EnergyComponent]
	Heat         *Store[component.HeatComponent]
	Shield       *Store[component.ShieldComponent]
	Boost        *Store[component.BoostComponent]
	Weapon       *Store[component.WeaponComponent]
	Orb          *Store[component.OrbComponent]
	Ping         *Store[component.PingComponent]
	CursorView   *Store[component.CursorViewComponent]
	Particle     *Store[component.ParticleComponent]
	Cleaner      *Store[component.CleanerComponent]
	Dust         *Store[component.DustComponent]
	Navigation   *Store[component.NavigationComponent]
	Combat       *Store[component.CombatComponent]
	Genotype     *Store[component.GenotypeComponent]
	Lightning    *Store[component.LightningComponent]
	Missile      *Store[component.MissileComponent]
	Mount        *Store[component.MountComponent]
	Beam         *Store[component.BeamComponent]
	Spirit       *Store[component.SpiritComponent]
	Materialize  *Store[component.MaterializeComponent]
	Target       *Store[component.TargetComponent]
	TargetAnchor *Store[component.TargetAnchorComponent]
	Drain        *Store[component.DrainComponent]
	Quasar       *Store[component.QuasarComponent]
	Swarm        *Store[component.SwarmComponent]
	Storm        *Store[component.StormComponent]
	StormCircle  *Store[component.StormCircleComponent]
	Bullet       *Store[component.BulletComponent]
	Pylon        *Store[component.PylonComponent]
	Snake        *Store[component.SnakeComponent]
	SnakeHead    *Store[component.SnakeHeadComponent]
	SnakeBody    *Store[component.SnakeBodyComponent]
	SnakeMember  *Store[component.SnakeMemberComponent]
	Eye          *Store[component.EyeComponent]
	Tower        *Store[component.TowerComponent]
	Kraken       *Store[component.KrakenComponent]
	Header       *Store[component.HeaderComponent]
	Member       *Store[component.MemberComponent]
	Flash        *Store[component.FlashComponent]
	Fadeout      *Store[component.FadeoutComponent]
	Splash       *Store[component.SplashComponent]
	Marker       *Store[component.MarkerComponent]
	Death        *Store[component.DeathComponent]
	Timer        *Store[component.TimerComponent]
}

// initComponents creates all component stores
// Called once from NewWorld()
func initComponents(w *World) {
	w.Components.Glyph = NewStore[component.GlyphComponent](w, GlyphBit)
	w.Components.Sigil = NewStore[component.SigilComponent](w, SigilBit)
	w.Components.Nugget = NewStore[component.NuggetComponent](w, NuggetBit)
	w.Components.Cursor = NewStore[component.CursorComponent](w, CursorBit)
	w.Components.Protection = NewStore[component.ProtectionComponent](w, ProtectionBit)
	w.Components.Kinetic = NewStore[component.KineticComponent](w, KineticBit)
	w.Components.Wall = NewStore[component.WallComponent](w, WallBit)
	w.Components.Loot = NewStore[component.LootComponent](w, LootBit)
	w.Components.Gateway = NewStore[component.GatewayComponent](w, GatewayBit)
	w.Components.Energy = NewStore[component.EnergyComponent](w, EnergyBit)
	w.Components.Heat = NewStore[component.HeatComponent](w, HeatBit)
	w.Components.Shield = NewStore[component.ShieldComponent](w, ShieldBit)
	w.Components.Boost = NewStore[component.BoostComponent](w, BoostBit)
	w.Components.Weapon = NewStore[component.WeaponComponent](w, WeaponBit)
	w.Components.Orb = NewStore[component.OrbComponent](w, OrbBit)
	w.Components.Ping = NewStore[component.PingComponent](w, PingBit)
	w.Components.CursorView = NewStore[component.CursorViewComponent](w, CursorViewBit)
	w.Components.Particle = NewStore[component.ParticleComponent](w, ParticleBit)
	w.Components.Cleaner = NewStore[component.CleanerComponent](w, CleanerBit)
	w.Components.Dust = NewStore[component.DustComponent](w, DustBit)
	w.Components.Navigation = NewStore[component.NavigationComponent](w, NavigationBit)
	w.Components.Combat = NewStore[component.CombatComponent](w, CombatBit)
	w.Components.Genotype = NewStore[component.GenotypeComponent](w, GenotypeBit)
	w.Components.Lightning = NewStore[component.LightningComponent](w, LightningBit)
	w.Components.Missile = NewStore[component.MissileComponent](w, MissileBit)
	w.Components.Mount = NewStore[component.MountComponent](w, MountBit)
	w.Components.Beam = NewStore[component.BeamComponent](w, BeamBit)
	w.Components.Spirit = NewStore[component.SpiritComponent](w, SpiritBit)
	w.Components.Materialize = NewStore[component.MaterializeComponent](w, MaterializeBit)
	w.Components.Target = NewStore[component.TargetComponent](w, TargetBit)
	w.Components.TargetAnchor = NewStore[component.TargetAnchorComponent](w, TargetAnchorBit)
	w.Components.Drain = NewStore[component.DrainComponent](w, DrainBit)
	w.Components.Quasar = NewStore[component.QuasarComponent](w, QuasarBit)
	w.Components.Swarm = NewStore[component.SwarmComponent](w, SwarmBit)
	w.Components.Storm = NewStore[component.StormComponent](w, StormBit)
	w.Components.StormCircle = NewStore[component.StormCircleComponent](w, StormCircleBit)
	w.Components.Bullet = NewStore[component.BulletComponent](w, BulletBit)
	w.Components.Pylon = NewStore[component.PylonComponent](w, PylonBit)
	w.Components.Snake = NewStore[component.SnakeComponent](w, SnakeBit)
	w.Components.SnakeHead = NewStore[component.SnakeHeadComponent](w, SnakeHeadBit)
	w.Components.SnakeBody = NewStore[component.SnakeBodyComponent](w, SnakeBodyBit)
	w.Components.SnakeMember = NewStore[component.SnakeMemberComponent](w, SnakeMemberBit)
	w.Components.Eye = NewStore[component.EyeComponent](w, EyeBit)
	w.Components.Tower = NewStore[component.TowerComponent](w, TowerBit)
	w.Components.Kraken = NewStore[component.KrakenComponent](w, KrakenBit)
	w.Components.Header = NewStore[component.HeaderComponent](w, HeaderBit)
	w.Components.Member = NewStore[component.MemberComponent](w, MemberBit)
	w.Components.Flash = NewStore[component.FlashComponent](w, FlashBit)
	w.Components.Fadeout = NewStore[component.FadeoutComponent](w, FadeoutBit)
	w.Components.Splash = NewStore[component.SplashComponent](w, SplashBit)
	w.Components.Marker = NewStore[component.MarkerComponent](w, MarkerBit)
	w.Components.Death = NewStore[component.DeathComponent](w, DeathBit)
	w.Components.Timer = NewStore[component.TimerComponent](w, TimerBit)
	w.Positions = NewPosition(w, PositionBit)
}

// removeEntity removes entity from every component store
// Caller MUST hold updateMutex
func (w *World) removeEntity(e core.Entity) {

	// Guard against unallocated entity
	mask, ok := w.componentMask[e]
	if !ok {
		return
	}

	// O(1) Fast-Path: If the entity has no components, exit immediately
	if mask == 0 {
		delete(w.componentMask, e)
		return
	}

	// O(1) Skip: Only invoke removal on stores where the bit is strictly present
	if mask&GlyphBit != 0 {
		w.Components.Glyph.RemoveEntity(e, true)
	}
	if mask&SigilBit != 0 {
		w.Components.Sigil.RemoveEntity(e, true)
	}
	if mask&NuggetBit != 0 {
		w.Components.Nugget.RemoveEntity(e, true)
	}
	if mask&CursorBit != 0 {
		w.Components.Cursor.RemoveEntity(e, true)
	}
	if mask&ProtectionBit != 0 {
		w.Components.Protection.RemoveEntity(e, true)
	}
	if mask&KineticBit != 0 {
		w.Components.Kinetic.RemoveEntity(e, true)
	}
	if mask&WallBit != 0 {
		w.Components.Wall.RemoveEntity(e, true)
	}
	if mask&LootBit != 0 {
		w.Components.Loot.RemoveEntity(e, true)
	}
	if mask&GatewayBit != 0 {
		w.Components.Gateway.RemoveEntity(e, true)
	}
	if mask&EnergyBit != 0 {
		w.Components.Energy.RemoveEntity(e, true)
	}
	if mask&HeatBit != 0 {
		w.Components.Heat.RemoveEntity(e, true)
	}
	if mask&ShieldBit != 0 {
		w.Components.Shield.RemoveEntity(e, true)
	}
	if mask&BoostBit != 0 {
		w.Components.Boost.RemoveEntity(e, true)
	}
	if mask&WeaponBit != 0 {
		w.Components.Weapon.RemoveEntity(e, true)
	}
	if mask&OrbBit != 0 {
		w.Components.Orb.RemoveEntity(e, true)
	}
	if mask&PingBit != 0 {
		w.Components.Ping.RemoveEntity(e, true)
	}
	if mask&CursorViewBit != 0 {
		w.Components.CursorView.RemoveEntity(e, true)
	}
	if mask&ParticleBit != 0 {
		w.Components.Particle.RemoveEntity(e, true)
	}
	if mask&CleanerBit != 0 {
		w.Components.Cleaner.RemoveEntity(e, true)
	}
	if mask&DustBit != 0 {
		w.Components.Dust.RemoveEntity(e, true)
	}
	if mask&NavigationBit != 0 {
		w.Components.Navigation.RemoveEntity(e, true)
	}
	if mask&CombatBit != 0 {
		w.Components.Combat.RemoveEntity(e, true)
	}
	if mask&GenotypeBit != 0 {
		w.Components.Genotype.RemoveEntity(e, true)
	}
	if mask&LightningBit != 0 {
		w.Components.Lightning.RemoveEntity(e, true)
	}
	if mask&MissileBit != 0 {
		w.Components.Missile.RemoveEntity(e, true)
	}
	if mask&MountBit != 0 {
		w.Components.Mount.RemoveEntity(e, true)
	}
	if mask&BeamBit != 0 {
		w.Components.Beam.RemoveEntity(e, true)
	}
	if mask&SpiritBit != 0 {
		w.Components.Spirit.RemoveEntity(e, true)
	}
	if mask&MaterializeBit != 0 {
		w.Components.Materialize.RemoveEntity(e, true)
	}
	if mask&TargetBit != 0 {
		w.Components.Target.RemoveEntity(e, true)
	}
	if mask&TargetAnchorBit != 0 {
		w.Components.TargetAnchor.RemoveEntity(e, true)
	}
	if mask&DrainBit != 0 {
		w.Components.Drain.RemoveEntity(e, true)
	}
	if mask&QuasarBit != 0 {
		w.Components.Quasar.RemoveEntity(e, true)
	}
	if mask&SwarmBit != 0 {
		w.Components.Swarm.RemoveEntity(e, true)
	}
	if mask&StormBit != 0 {
		w.Components.Storm.RemoveEntity(e, true)
	}
	if mask&StormCircleBit != 0 {
		w.Components.StormCircle.RemoveEntity(e, true)
	}
	if mask&BulletBit != 0 {
		w.Components.Bullet.RemoveEntity(e, true)
	}
	if mask&PylonBit != 0 {
		w.Components.Pylon.RemoveEntity(e, true)
	}
	if mask&SnakeBit != 0 {
		w.Components.Snake.RemoveEntity(e, true)
	}
	if mask&SnakeHeadBit != 0 {
		w.Components.SnakeHead.RemoveEntity(e, true)
	}
	if mask&SnakeBodyBit != 0 {
		w.Components.SnakeBody.RemoveEntity(e, true)
	}
	if mask&SnakeMemberBit != 0 {
		w.Components.SnakeMember.RemoveEntity(e, true)
	}
	if mask&EyeBit != 0 {
		w.Components.Eye.RemoveEntity(e, true)
	}
	if mask&TowerBit != 0 {
		w.Components.Tower.RemoveEntity(e, true)
	}
	if mask&KrakenBit != 0 {
		w.Components.Kraken.RemoveEntity(e, true)
	}
	if mask&HeaderBit != 0 {
		w.Components.Header.RemoveEntity(e, true)
	}
	if mask&MemberBit != 0 {
		w.Components.Member.RemoveEntity(e, true)
	}
	if mask&FlashBit != 0 {
		w.Components.Flash.RemoveEntity(e, true)
	}
	if mask&FadeoutBit != 0 {
		w.Components.Fadeout.RemoveEntity(e, true)
	}
	if mask&SplashBit != 0 {
		w.Components.Splash.RemoveEntity(e, true)
	}
	if mask&MarkerBit != 0 {
		w.Components.Marker.RemoveEntity(e, true)
	}
	if mask&DeathBit != 0 {
		w.Components.Death.RemoveEntity(e, true)
	}
	if mask&TimerBit != 0 {
		w.Components.Timer.RemoveEntity(e, true)
	}
	if mask&PositionBit != 0 {
		w.Positions.RemoveEntity(e, true)
	}

	// Remove entity from component mask
	delete(w.componentMask, e)
}

// removeEntitiesBatch removes entities from all stores using batch operations
// Caller MUST hold updateMutex
func (w *World) removeEntitiesBatch(entities []core.Entity) {
	// Union of component signatures: skip every store no entity touches
	var union uint64
	for _, e := range entities {
		union |= w.componentMask[e]
	}
	if union == 0 {
		for _, e := range entities {
			delete(w.componentMask, e)
		}
		return
	}
	if union&GlyphBit != 0 {
		w.Components.Glyph.RemoveBatch(entities, true)
	}
	if union&SigilBit != 0 {
		w.Components.Sigil.RemoveBatch(entities, true)
	}
	if union&NuggetBit != 0 {
		w.Components.Nugget.RemoveBatch(entities, true)
	}
	if union&CursorBit != 0 {
		w.Components.Cursor.RemoveBatch(entities, true)
	}
	if union&ProtectionBit != 0 {
		w.Components.Protection.RemoveBatch(entities, true)
	}
	if union&KineticBit != 0 {
		w.Components.Kinetic.RemoveBatch(entities, true)
	}
	if union&WallBit != 0 {
		w.Components.Wall.RemoveBatch(entities, true)
	}
	if union&LootBit != 0 {
		w.Components.Loot.RemoveBatch(entities, true)
	}
	if union&GatewayBit != 0 {
		w.Components.Gateway.RemoveBatch(entities, true)
	}
	if union&EnergyBit != 0 {
		w.Components.Energy.RemoveBatch(entities, true)
	}
	if union&HeatBit != 0 {
		w.Components.Heat.RemoveBatch(entities, true)
	}
	if union&ShieldBit != 0 {
		w.Components.Shield.RemoveBatch(entities, true)
	}
	if union&BoostBit != 0 {
		w.Components.Boost.RemoveBatch(entities, true)
	}
	if union&WeaponBit != 0 {
		w.Components.Weapon.RemoveBatch(entities, true)
	}
	if union&OrbBit != 0 {
		w.Components.Orb.RemoveBatch(entities, true)
	}
	if union&PingBit != 0 {
		w.Components.Ping.RemoveBatch(entities, true)
	}
	if union&CursorViewBit != 0 {
		w.Components.CursorView.RemoveBatch(entities, true)
	}
	if union&ParticleBit != 0 {
		w.Components.Particle.RemoveBatch(entities, true)
	}
	if union&CleanerBit != 0 {
		w.Components.Cleaner.RemoveBatch(entities, true)
	}
	if union&DustBit != 0 {
		w.Components.Dust.RemoveBatch(entities, true)
	}
	if union&NavigationBit != 0 {
		w.Components.Navigation.RemoveBatch(entities, true)
	}
	if union&CombatBit != 0 {
		w.Components.Combat.RemoveBatch(entities, true)
	}
	if union&GenotypeBit != 0 {
		w.Components.Genotype.RemoveBatch(entities, true)
	}
	if union&LightningBit != 0 {
		w.Components.Lightning.RemoveBatch(entities, true)
	}
	if union&MissileBit != 0 {
		w.Components.Missile.RemoveBatch(entities, true)
	}
	if union&MountBit != 0 {
		w.Components.Mount.RemoveBatch(entities, true)
	}
	if union&BeamBit != 0 {
		w.Components.Beam.RemoveBatch(entities, true)
	}
	if union&SpiritBit != 0 {
		w.Components.Spirit.RemoveBatch(entities, true)
	}
	if union&MaterializeBit != 0 {
		w.Components.Materialize.RemoveBatch(entities, true)
	}
	if union&TargetBit != 0 {
		w.Components.Target.RemoveBatch(entities, true)
	}
	if union&TargetAnchorBit != 0 {
		w.Components.TargetAnchor.RemoveBatch(entities, true)
	}
	if union&DrainBit != 0 {
		w.Components.Drain.RemoveBatch(entities, true)
	}
	if union&QuasarBit != 0 {
		w.Components.Quasar.RemoveBatch(entities, true)
	}
	if union&SwarmBit != 0 {
		w.Components.Swarm.RemoveBatch(entities, true)
	}
	if union&StormBit != 0 {
		w.Components.Storm.RemoveBatch(entities, true)
	}
	if union&StormCircleBit != 0 {
		w.Components.StormCircle.RemoveBatch(entities, true)
	}
	if union&BulletBit != 0 {
		w.Components.Bullet.RemoveBatch(entities, true)
	}
	if union&PylonBit != 0 {
		w.Components.Pylon.RemoveBatch(entities, true)
	}
	if union&SnakeBit != 0 {
		w.Components.Snake.RemoveBatch(entities, true)
	}
	if union&SnakeHeadBit != 0 {
		w.Components.SnakeHead.RemoveBatch(entities, true)
	}
	if union&SnakeBodyBit != 0 {
		w.Components.SnakeBody.RemoveBatch(entities, true)
	}
	if union&SnakeMemberBit != 0 {
		w.Components.SnakeMember.RemoveBatch(entities, true)
	}
	if union&EyeBit != 0 {
		w.Components.Eye.RemoveBatch(entities, true)
	}
	if union&TowerBit != 0 {
		w.Components.Tower.RemoveBatch(entities, true)
	}
	if union&KrakenBit != 0 {
		w.Components.Kraken.RemoveBatch(entities, true)
	}
	if union&HeaderBit != 0 {
		w.Components.Header.RemoveBatch(entities, true)
	}
	if union&MemberBit != 0 {
		w.Components.Member.RemoveBatch(entities, true)
	}
	if union&FlashBit != 0 {
		w.Components.Flash.RemoveBatch(entities, true)
	}
	if union&FadeoutBit != 0 {
		w.Components.Fadeout.RemoveBatch(entities, true)
	}
	if union&SplashBit != 0 {
		w.Components.Splash.RemoveBatch(entities, true)
	}
	if union&MarkerBit != 0 {
		w.Components.Marker.RemoveBatch(entities, true)
	}
	if union&DeathBit != 0 {
		w.Components.Death.RemoveBatch(entities, true)
	}
	if union&TimerBit != 0 {
		w.Components.Timer.RemoveBatch(entities, true)
	}
	if union&PositionBit != 0 {
		w.Positions.RemoveBatch(entities, true)
	}

	for _, e := range entities {
		delete(w.componentMask, e)
	}
}

// wipeAll clears all component stores
// Caller MUST hold updateMutex
func (w *World) wipeAll() {
	w.Components.Glyph.ClearAllComponents()
	w.Components.Sigil.ClearAllComponents()
	w.Components.Nugget.ClearAllComponents()
	w.Components.Cursor.ClearAllComponents()
	w.Components.Protection.ClearAllComponents()
	w.Components.Kinetic.ClearAllComponents()
	w.Components.Wall.ClearAllComponents()
	w.Components.Loot.ClearAllComponents()
	w.Components.Gateway.ClearAllComponents()
	w.Components.Energy.ClearAllComponents()
	w.Components.Heat.ClearAllComponents()
	w.Components.Shield.ClearAllComponents()
	w.Components.Boost.ClearAllComponents()
	w.Components.Weapon.ClearAllComponents()
	w.Components.Orb.ClearAllComponents()
	w.Components.Ping.ClearAllComponents()
	w.Components.CursorView.ClearAllComponents()
	w.Components.Particle.ClearAllComponents()
	w.Components.Cleaner.ClearAllComponents()
	w.Components.Dust.ClearAllComponents()
	w.Components.Navigation.ClearAllComponents()
	w.Components.Combat.ClearAllComponents()
	w.Components.Genotype.ClearAllComponents()
	w.Components.Lightning.ClearAllComponents()
	w.Components.Missile.ClearAllComponents()
	w.Components.Mount.ClearAllComponents()
	w.Components.Beam.ClearAllComponents()
	w.Components.Spirit.ClearAllComponents()
	w.Components.Materialize.ClearAllComponents()
	w.Components.Target.ClearAllComponents()
	w.Components.TargetAnchor.ClearAllComponents()
	w.Components.Drain.ClearAllComponents()
	w.Components.Quasar.ClearAllComponents()
	w.Components.Swarm.ClearAllComponents()
	w.Components.Storm.ClearAllComponents()
	w.Components.StormCircle.ClearAllComponents()
	w.Components.Bullet.ClearAllComponents()
	w.Components.Pylon.ClearAllComponents()
	w.Components.Snake.ClearAllComponents()
	w.Components.SnakeHead.ClearAllComponents()
	w.Components.SnakeBody.ClearAllComponents()
	w.Components.SnakeMember.ClearAllComponents()
	w.Components.Eye.ClearAllComponents()
	w.Components.Tower.ClearAllComponents()
	w.Components.Kraken.ClearAllComponents()
	w.Components.Header.ClearAllComponents()
	w.Components.Member.ClearAllComponents()
	w.Components.Flash.ClearAllComponents()
	w.Components.Fadeout.ClearAllComponents()
	w.Components.Splash.ClearAllComponents()
	w.Components.Marker.ClearAllComponents()
	w.Components.Death.ClearAllComponents()
	w.Components.Timer.ClearAllComponents()
	w.Positions.ClearAllComponents()

	// Clear component mask
	clear(w.componentMask)
}
