// Code generated by gen-manifest; DO NOT EDIT.

package engine

import "github.com/lixenwraith/vif/internal/core"

// componentRule names the entity domain a component bit may attach to
type componentRule struct {
	field  string
	domain core.Domain
}

// componentDomains is the audit table for AddComponentMask, derived from
// manifest.Components. A bit absent here attaches in either domain.
var componentDomains = map[uint64]componentRule{
	NuggetBit:       {"Nugget", core.DomainPlayer},
	CursorBit:       {"Cursor", core.DomainShared},
	WallBit:         {"Wall", core.DomainShared},
	LootBit:         {"Loot", core.DomainPlayer},
	GatewayBit:      {"Gateway", core.DomainShared},
	EnergyBit:       {"Energy", core.DomainShared},
	HeatBit:         {"Heat", core.DomainShared},
	BoostBit:        {"Boost", core.DomainShared},
	WeaponBit:       {"Weapon", core.DomainShared},
	OrbBit:          {"Orb", core.DomainPlayer},
	PingBit:         {"Ping", core.DomainShared},
	CursorViewBit:   {"CursorView", core.DomainShared},
	ParticleBit:     {"Particle", core.DomainPlayer},
	DustBit:         {"Dust", core.DomainPlayer},
	GenotypeBit:     {"Genotype", core.DomainShared},
	LightningBit:    {"Lightning", core.DomainPlayer},
	MissileBit:      {"Missile", core.DomainPlayer},
	MountBit:        {"Mount", core.DomainShared},
	TargetBit:       {"Target", core.DomainShared},
	TargetAnchorBit: {"TargetAnchor", core.DomainShared},
	DrainBit:        {"Drain", core.DomainPlayer},
	QuasarBit:       {"Quasar", core.DomainShared},
	SwarmBit:        {"Swarm", core.DomainShared},
	StormBit:        {"Storm", core.DomainShared},
	StormCircleBit:  {"StormCircle", core.DomainShared},
	BulletBit:       {"Bullet", core.DomainPlayer},
	PylonBit:        {"Pylon", core.DomainShared},
	SnakeBit:        {"Snake", core.DomainShared},
	SnakeHeadBit:    {"SnakeHead", core.DomainShared},
	SnakeBodyBit:    {"SnakeBody", core.DomainShared},
	SnakeMemberBit:  {"SnakeMember", core.DomainShared},
	EyeBit:          {"Eye", core.DomainShared},
	TowerBit:        {"Tower", core.DomainShared},
	KrakenBit:       {"Kraken", core.DomainShared},
	HeaderBit:       {"Header", core.DomainShared},
	MemberBit:       {"Member", core.DomainShared},
	FlashBit:        {"Flash", core.DomainPlayer},
	FadeoutBit:      {"Fadeout", core.DomainPlayer},
	SplashBit:       {"Splash", core.DomainPlayer},
}
