// Code generated by gen-manifest; DO NOT EDIT.

package engine

import (
	"slices"

	"github.com/lixenwraith/vif/internal/component"
	"github.com/lixenwraith/vif/internal/core"
)

// StoreEntry is one entity's component in a capture. The reference is a
// core.Entity, never a dense index: dense positions are an artifact of insertion
// order on the instance that produced them and mean nothing on any other.
type StoreEntry[T any] struct {
	Entity core.Entity `json:"e"`
	Value  T           `json:"v"`
}

// SharedWorldState is every shared-domain component in the world, by store, plus
// the placements and the allocator counters. Player-domain entities are excluded
// at capture: a snapshot describes the shared world and nothing else (D-1, D-6),
// and a participant's own simulation does not exist on any other instance (D-2).
type SharedWorldState struct {
	// NextEntity is the shared allocator's next ID. It travels because entity
	// identity is shared state: an installed world that allocated from a different
	// counter would give the next spawned entity an ID the sender used for
	// something else.
	NextEntity uint64 `json:"next_entity"`

	// Created and Destroyed are the shared domain's lifetime counters. They are in
	// the compared surface, because two participants creating and destroying the
	// same shared entities must agree on how many there have been; an installed
	// world reporting its own totals disagrees from the tick it arrives.
	Created   int64 `json:"created"`
	Destroyed int64 `json:"destroyed"`

	Positions    []StoreEntry[component.PositionComponent]     `json:"positions,omitempty"`
	Glyph        []StoreEntry[component.GlyphComponent]        `json:"glyph,omitempty"`
	Sigil        []StoreEntry[component.SigilComponent]        `json:"sigil,omitempty"`
	Nugget       []StoreEntry[component.NuggetComponent]       `json:"nugget,omitempty"`
	Cursor       []StoreEntry[component.CursorComponent]       `json:"cursor,omitempty"`
	Protection   []StoreEntry[component.ProtectionComponent]   `json:"protection,omitempty"`
	Kinetic      []StoreEntry[component.KineticComponent]      `json:"kinetic,omitempty"`
	Wall         []StoreEntry[component.WallComponent]         `json:"wall,omitempty"`
	Loot         []StoreEntry[component.LootComponent]         `json:"loot,omitempty"`
	Gateway      []StoreEntry[component.GatewayComponent]      `json:"gateway,omitempty"`
	Energy       []StoreEntry[component.EnergyComponent]       `json:"energy,omitempty"`
	Heat         []StoreEntry[component.HeatComponent]         `json:"heat,omitempty"`
	Shield       []StoreEntry[component.ShieldComponent]       `json:"shield,omitempty"`
	Boost        []StoreEntry[component.BoostComponent]        `json:"boost,omitempty"`
	Weapon       []StoreEntry[component.WeaponComponent]       `json:"weapon,omitempty"`
	Orb          []StoreEntry[component.OrbComponent]          `json:"orb,omitempty"`
	Ping         []StoreEntry[component.PingComponent]         `json:"ping,omitempty"`
	CursorView   []StoreEntry[component.CursorViewComponent]   `json:"cursorview,omitempty"`
	Particle     []StoreEntry[component.ParticleComponent]     `json:"particle,omitempty"`
	Cleaner      []StoreEntry[component.CleanerComponent]      `json:"cleaner,omitempty"`
	Dust         []StoreEntry[component.DustComponent]         `json:"dust,omitempty"`
	Navigation   []StoreEntry[component.NavigationComponent]   `json:"navigation,omitempty"`
	Combat       []StoreEntry[component.CombatComponent]       `json:"combat,omitempty"`
	Genotype     []StoreEntry[component.GenotypeComponent]     `json:"genotype,omitempty"`
	Lightning    []StoreEntry[component.LightningComponent]    `json:"lightning,omitempty"`
	Missile      []StoreEntry[component.MissileComponent]      `json:"missile,omitempty"`
	Mount        []StoreEntry[component.MountComponent]        `json:"mount,omitempty"`
	Ray          []StoreEntry[component.RayComponent]          `json:"ray,omitempty"`
	Spirit       []StoreEntry[component.SpiritComponent]       `json:"spirit,omitempty"`
	Materialize  []StoreEntry[component.MaterializeComponent]  `json:"materialize,omitempty"`
	Target       []StoreEntry[component.TargetComponent]       `json:"target,omitempty"`
	TargetAnchor []StoreEntry[component.TargetAnchorComponent] `json:"targetanchor,omitempty"`
	Drain        []StoreEntry[component.DrainComponent]        `json:"drain,omitempty"`
	Quasar       []StoreEntry[component.QuasarComponent]       `json:"quasar,omitempty"`
	Swarm        []StoreEntry[component.SwarmComponent]        `json:"swarm,omitempty"`
	Storm        []StoreEntry[component.StormComponent]        `json:"storm,omitempty"`
	StormCircle  []StoreEntry[component.StormCircleComponent]  `json:"stormcircle,omitempty"`
	Bullet       []StoreEntry[component.BulletComponent]       `json:"bullet,omitempty"`
	Pylon        []StoreEntry[component.PylonComponent]        `json:"pylon,omitempty"`
	Snake        []StoreEntry[component.SnakeComponent]        `json:"snake,omitempty"`
	SnakeHead    []StoreEntry[component.SnakeHeadComponent]    `json:"snakehead,omitempty"`
	SnakeBody    []StoreEntry[component.SnakeBodyComponent]    `json:"snakebody,omitempty"`
	SnakeMember  []StoreEntry[component.SnakeMemberComponent]  `json:"snakemember,omitempty"`
	Eye          []StoreEntry[component.EyeComponent]          `json:"eye,omitempty"`
	Tower        []StoreEntry[component.TowerComponent]        `json:"tower,omitempty"`
	Kraken       []StoreEntry[component.KrakenComponent]       `json:"kraken,omitempty"`
	Header       []StoreEntry[component.HeaderComponent]       `json:"header,omitempty"`
	Member       []StoreEntry[component.MemberComponent]       `json:"member,omitempty"`
	Flash        []StoreEntry[component.FlashComponent]        `json:"flash,omitempty"`
	Fadeout      []StoreEntry[component.FadeoutComponent]      `json:"fadeout,omitempty"`
	Splash       []StoreEntry[component.SplashComponent]       `json:"splash,omitempty"`
	Marker       []StoreEntry[component.MarkerComponent]       `json:"marker,omitempty"`
	Death        []StoreEntry[component.DeathComponent]        `json:"death,omitempty"`
	Timer        []StoreEntry[component.TimerComponent]        `json:"timer,omitempty"`
}

// CaptureSharedWorld reads every shared entity's components into a transferable
// value. Entities are emitted in store order, which is the order the receiving
// instance re-inserts them in, so a capture of an installed world equals the
// capture it was installed from.
//
// Caller MUST hold updateMutex: this reads every store.
func (w *World) CaptureSharedWorld() SharedWorldState {
	var s SharedWorldState
	s.NextEntity = w.nextEntityID[core.DomainShared]
	s.Created = w.createdCount[core.DomainShared].Load()
	s.Destroyed = w.destroyedCount[core.DomainShared].Load()

	for _, e := range w.Positions.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Positions.GetPosition(e); ok {
			s.Positions = append(s.Positions, StoreEntry[component.PositionComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Glyph.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Glyph.GetComponent(e); ok {
			s.Glyph = append(s.Glyph, StoreEntry[component.GlyphComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Sigil.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Sigil.GetComponent(e); ok {
			s.Sigil = append(s.Sigil, StoreEntry[component.SigilComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Nugget.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Nugget.GetComponent(e); ok {
			s.Nugget = append(s.Nugget, StoreEntry[component.NuggetComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Cursor.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Cursor.GetComponent(e); ok {
			s.Cursor = append(s.Cursor, StoreEntry[component.CursorComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Protection.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Protection.GetComponent(e); ok {
			s.Protection = append(s.Protection, StoreEntry[component.ProtectionComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Kinetic.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Kinetic.GetComponent(e); ok {
			s.Kinetic = append(s.Kinetic, StoreEntry[component.KineticComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Wall.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Wall.GetComponent(e); ok {
			s.Wall = append(s.Wall, StoreEntry[component.WallComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Loot.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Loot.GetComponent(e); ok {
			s.Loot = append(s.Loot, StoreEntry[component.LootComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Gateway.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Gateway.GetComponent(e); ok {
			s.Gateway = append(s.Gateway, StoreEntry[component.GatewayComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Energy.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Energy.GetComponent(e); ok {
			s.Energy = append(s.Energy, StoreEntry[component.EnergyComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Heat.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Heat.GetComponent(e); ok {
			s.Heat = append(s.Heat, StoreEntry[component.HeatComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Shield.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Shield.GetComponent(e); ok {
			s.Shield = append(s.Shield, StoreEntry[component.ShieldComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Boost.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Boost.GetComponent(e); ok {
			s.Boost = append(s.Boost, StoreEntry[component.BoostComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Weapon.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Weapon.GetComponent(e); ok {
			s.Weapon = append(s.Weapon, StoreEntry[component.WeaponComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Orb.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Orb.GetComponent(e); ok {
			s.Orb = append(s.Orb, StoreEntry[component.OrbComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Ping.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Ping.GetComponent(e); ok {
			s.Ping = append(s.Ping, StoreEntry[component.PingComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.CursorView.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.CursorView.GetComponent(e); ok {
			s.CursorView = append(s.CursorView, StoreEntry[component.CursorViewComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Particle.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Particle.GetComponent(e); ok {
			s.Particle = append(s.Particle, StoreEntry[component.ParticleComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Cleaner.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Cleaner.GetComponent(e); ok {
			s.Cleaner = append(s.Cleaner, StoreEntry[component.CleanerComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Dust.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Dust.GetComponent(e); ok {
			s.Dust = append(s.Dust, StoreEntry[component.DustComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Navigation.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Navigation.GetComponent(e); ok {
			s.Navigation = append(s.Navigation, StoreEntry[component.NavigationComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Combat.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Combat.GetComponent(e); ok {
			s.Combat = append(s.Combat, StoreEntry[component.CombatComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Genotype.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Genotype.GetComponent(e); ok {
			s.Genotype = append(s.Genotype, StoreEntry[component.GenotypeComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Lightning.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Lightning.GetComponent(e); ok {
			s.Lightning = append(s.Lightning, StoreEntry[component.LightningComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Missile.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Missile.GetComponent(e); ok {
			s.Missile = append(s.Missile, StoreEntry[component.MissileComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Mount.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Mount.GetComponent(e); ok {
			s.Mount = append(s.Mount, StoreEntry[component.MountComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Ray.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Ray.GetComponent(e); ok {
			s.Ray = append(s.Ray, StoreEntry[component.RayComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Spirit.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Spirit.GetComponent(e); ok {
			s.Spirit = append(s.Spirit, StoreEntry[component.SpiritComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Materialize.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Materialize.GetComponent(e); ok {
			s.Materialize = append(s.Materialize, StoreEntry[component.MaterializeComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Target.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Target.GetComponent(e); ok {
			s.Target = append(s.Target, StoreEntry[component.TargetComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.TargetAnchor.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.TargetAnchor.GetComponent(e); ok {
			s.TargetAnchor = append(s.TargetAnchor, StoreEntry[component.TargetAnchorComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Drain.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Drain.GetComponent(e); ok {
			s.Drain = append(s.Drain, StoreEntry[component.DrainComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Quasar.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Quasar.GetComponent(e); ok {
			s.Quasar = append(s.Quasar, StoreEntry[component.QuasarComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Swarm.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Swarm.GetComponent(e); ok {
			s.Swarm = append(s.Swarm, StoreEntry[component.SwarmComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Storm.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Storm.GetComponent(e); ok {
			s.Storm = append(s.Storm, StoreEntry[component.StormComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.StormCircle.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.StormCircle.GetComponent(e); ok {
			s.StormCircle = append(s.StormCircle, StoreEntry[component.StormCircleComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Bullet.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Bullet.GetComponent(e); ok {
			s.Bullet = append(s.Bullet, StoreEntry[component.BulletComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Pylon.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Pylon.GetComponent(e); ok {
			s.Pylon = append(s.Pylon, StoreEntry[component.PylonComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Snake.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Snake.GetComponent(e); ok {
			s.Snake = append(s.Snake, StoreEntry[component.SnakeComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.SnakeHead.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.SnakeHead.GetComponent(e); ok {
			s.SnakeHead = append(s.SnakeHead, StoreEntry[component.SnakeHeadComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.SnakeBody.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.SnakeBody.GetComponent(e); ok {
			s.SnakeBody = append(s.SnakeBody, StoreEntry[component.SnakeBodyComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.SnakeMember.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.SnakeMember.GetComponent(e); ok {
			s.SnakeMember = append(s.SnakeMember, StoreEntry[component.SnakeMemberComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Eye.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Eye.GetComponent(e); ok {
			s.Eye = append(s.Eye, StoreEntry[component.EyeComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Tower.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Tower.GetComponent(e); ok {
			s.Tower = append(s.Tower, StoreEntry[component.TowerComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Kraken.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Kraken.GetComponent(e); ok {
			s.Kraken = append(s.Kraken, StoreEntry[component.KrakenComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Header.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Header.GetComponent(e); ok {
			s.Header = append(s.Header, StoreEntry[component.HeaderComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Member.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Member.GetComponent(e); ok {
			s.Member = append(s.Member, StoreEntry[component.MemberComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Flash.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Flash.GetComponent(e); ok {
			s.Flash = append(s.Flash, StoreEntry[component.FlashComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Fadeout.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Fadeout.GetComponent(e); ok {
			s.Fadeout = append(s.Fadeout, StoreEntry[component.FadeoutComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Splash.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Splash.GetComponent(e); ok {
			s.Splash = append(s.Splash, StoreEntry[component.SplashComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Marker.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Marker.GetComponent(e); ok {
			s.Marker = append(s.Marker, StoreEntry[component.MarkerComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Death.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Death.GetComponent(e); ok {
			s.Death = append(s.Death, StoreEntry[component.DeathComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	for _, e := range w.Components.Timer.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Timer.GetComponent(e); ok {
			s.Timer = append(s.Timer, StoreEntry[component.TimerComponent]{Entity: e, Value: DetachSnapshotValue(v)})
		}
	}
	return s
}

// InstallSharedWorld replaces this world's shared half with a capture. Player
// entities are left untouched: they are this instance's own and no capture
// describes them.
//
// Caller MUST hold updateMutex.
func (w *World) InstallSharedWorld(s SharedWorldState) {
	w.clearSharedEntities()

	for _, en := range s.Positions {
		w.Positions.SetPosition(en.Entity, en.Value)
	}
	for _, en := range s.Glyph {
		w.Components.Glyph.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Sigil {
		w.Components.Sigil.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Nugget {
		w.Components.Nugget.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Cursor {
		w.Components.Cursor.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Protection {
		w.Components.Protection.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Kinetic {
		w.Components.Kinetic.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Wall {
		w.Components.Wall.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Loot {
		w.Components.Loot.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Gateway {
		w.Components.Gateway.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Energy {
		w.Components.Energy.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Heat {
		w.Components.Heat.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Shield {
		w.Components.Shield.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Boost {
		w.Components.Boost.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Weapon {
		w.Components.Weapon.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Orb {
		w.Components.Orb.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Ping {
		w.Components.Ping.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.CursorView {
		w.Components.CursorView.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Particle {
		w.Components.Particle.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Cleaner {
		w.Components.Cleaner.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Dust {
		w.Components.Dust.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Navigation {
		w.Components.Navigation.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Combat {
		w.Components.Combat.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Genotype {
		w.Components.Genotype.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Lightning {
		w.Components.Lightning.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Missile {
		w.Components.Missile.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Mount {
		w.Components.Mount.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Ray {
		w.Components.Ray.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Spirit {
		w.Components.Spirit.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Materialize {
		w.Components.Materialize.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Target {
		w.Components.Target.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.TargetAnchor {
		w.Components.TargetAnchor.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Drain {
		w.Components.Drain.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Quasar {
		w.Components.Quasar.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Swarm {
		w.Components.Swarm.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Storm {
		w.Components.Storm.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.StormCircle {
		w.Components.StormCircle.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Bullet {
		w.Components.Bullet.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Pylon {
		w.Components.Pylon.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Snake {
		w.Components.Snake.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.SnakeHead {
		w.Components.SnakeHead.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.SnakeBody {
		w.Components.SnakeBody.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.SnakeMember {
		w.Components.SnakeMember.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Eye {
		w.Components.Eye.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Tower {
		w.Components.Tower.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Kraken {
		w.Components.Kraken.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Header {
		w.Components.Header.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Member {
		w.Components.Member.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Flash {
		w.Components.Flash.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Fadeout {
		w.Components.Fadeout.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Splash {
		w.Components.Splash.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Marker {
		w.Components.Marker.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Death {
		w.Components.Death.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	for _, en := range s.Timer {
		w.Components.Timer.SetComponent(en.Entity, DetachSnapshotValue(en.Value))
	}
	if s.NextEntity > 0 {
		w.nextEntityID[core.DomainShared] = s.NextEntity
	}
	w.createdCount[core.DomainShared].Store(s.Created)
	w.destroyedCount[core.DomainShared].Store(s.Destroyed)

	// The spatial index is derived, not shipped: SetPosition above rebuilt it.
	// Its gauges are published on the status cadence, so republish them here —
	// they describe what was just installed, and they are in the compared surface.
	w.Positions.PublishTelemetry()
}

// SharedWorldDelta is one shared world expressed against another, store by store.
// Generated for the same reason the capture is: a component added to the manifest
// has to reach a correction without anyone remembering to add it, or the delta
// silently omits state the baseline then keeps forever.
//
// The scalars are carried whole. They are three numbers, and a delta that omitted
// an unchanged one would need a way to say "unchanged" that costs more than the
// number.
type SharedWorldDelta struct {
	NextEntity uint64 `json:"next_entity"`
	Created    int64  `json:"created"`
	Destroyed  int64  `json:"destroyed"`

	Positions    StoreDelta[component.PositionComponent]     `json:"positions,omitzero"`
	Glyph        StoreDelta[component.GlyphComponent]        `json:"glyph,omitzero"`
	Sigil        StoreDelta[component.SigilComponent]        `json:"sigil,omitzero"`
	Nugget       StoreDelta[component.NuggetComponent]       `json:"nugget,omitzero"`
	Cursor       StoreDelta[component.CursorComponent]       `json:"cursor,omitzero"`
	Protection   StoreDelta[component.ProtectionComponent]   `json:"protection,omitzero"`
	Kinetic      StoreDelta[component.KineticComponent]      `json:"kinetic,omitzero"`
	Wall         StoreDelta[component.WallComponent]         `json:"wall,omitzero"`
	Loot         StoreDelta[component.LootComponent]         `json:"loot,omitzero"`
	Gateway      StoreDelta[component.GatewayComponent]      `json:"gateway,omitzero"`
	Energy       StoreDelta[component.EnergyComponent]       `json:"energy,omitzero"`
	Heat         StoreDelta[component.HeatComponent]         `json:"heat,omitzero"`
	Shield       StoreDelta[component.ShieldComponent]       `json:"shield,omitzero"`
	Boost        StoreDelta[component.BoostComponent]        `json:"boost,omitzero"`
	Weapon       StoreDelta[component.WeaponComponent]       `json:"weapon,omitzero"`
	Orb          StoreDelta[component.OrbComponent]          `json:"orb,omitzero"`
	Ping         StoreDelta[component.PingComponent]         `json:"ping,omitzero"`
	CursorView   StoreDelta[component.CursorViewComponent]   `json:"cursorview,omitzero"`
	Particle     StoreDelta[component.ParticleComponent]     `json:"particle,omitzero"`
	Cleaner      StoreDelta[component.CleanerComponent]      `json:"cleaner,omitzero"`
	Dust         StoreDelta[component.DustComponent]         `json:"dust,omitzero"`
	Navigation   StoreDelta[component.NavigationComponent]   `json:"navigation,omitzero"`
	Combat       StoreDelta[component.CombatComponent]       `json:"combat,omitzero"`
	Genotype     StoreDelta[component.GenotypeComponent]     `json:"genotype,omitzero"`
	Lightning    StoreDelta[component.LightningComponent]    `json:"lightning,omitzero"`
	Missile      StoreDelta[component.MissileComponent]      `json:"missile,omitzero"`
	Mount        StoreDelta[component.MountComponent]        `json:"mount,omitzero"`
	Ray          StoreDelta[component.RayComponent]          `json:"ray,omitzero"`
	Spirit       StoreDelta[component.SpiritComponent]       `json:"spirit,omitzero"`
	Materialize  StoreDelta[component.MaterializeComponent]  `json:"materialize,omitzero"`
	Target       StoreDelta[component.TargetComponent]       `json:"target,omitzero"`
	TargetAnchor StoreDelta[component.TargetAnchorComponent] `json:"targetanchor,omitzero"`
	Drain        StoreDelta[component.DrainComponent]        `json:"drain,omitzero"`
	Quasar       StoreDelta[component.QuasarComponent]       `json:"quasar,omitzero"`
	Swarm        StoreDelta[component.SwarmComponent]        `json:"swarm,omitzero"`
	Storm        StoreDelta[component.StormComponent]        `json:"storm,omitzero"`
	StormCircle  StoreDelta[component.StormCircleComponent]  `json:"stormcircle,omitzero"`
	Bullet       StoreDelta[component.BulletComponent]       `json:"bullet,omitzero"`
	Pylon        StoreDelta[component.PylonComponent]        `json:"pylon,omitzero"`
	Snake        StoreDelta[component.SnakeComponent]        `json:"snake,omitzero"`
	SnakeHead    StoreDelta[component.SnakeHeadComponent]    `json:"snakehead,omitzero"`
	SnakeBody    StoreDelta[component.SnakeBodyComponent]    `json:"snakebody,omitzero"`
	SnakeMember  StoreDelta[component.SnakeMemberComponent]  `json:"snakemember,omitzero"`
	Eye          StoreDelta[component.EyeComponent]          `json:"eye,omitzero"`
	Tower        StoreDelta[component.TowerComponent]        `json:"tower,omitzero"`
	Kraken       StoreDelta[component.KrakenComponent]       `json:"kraken,omitzero"`
	Header       StoreDelta[component.HeaderComponent]       `json:"header,omitzero"`
	Member       StoreDelta[component.MemberComponent]       `json:"member,omitzero"`
	Flash        StoreDelta[component.FlashComponent]        `json:"flash,omitzero"`
	Fadeout      StoreDelta[component.FadeoutComponent]      `json:"fadeout,omitzero"`
	Splash       StoreDelta[component.SplashComponent]       `json:"splash,omitzero"`
	Marker       StoreDelta[component.MarkerComponent]       `json:"marker,omitzero"`
	Death        StoreDelta[component.DeathComponent]        `json:"death,omitzero"`
	Timer        StoreDelta[component.TimerComponent]        `json:"timer,omitzero"`
}

// DiffSharedWorld expresses next as a difference against base.
//
// Applying the result to base reproduces next exactly — same entries, same order —
// which is the property the receiver's integrity check depends on. Nothing here
// reads the world, so it runs on whatever goroutine took the two captures rather
// than under the world lock.
func DiffSharedWorld(base, next SharedWorldState) SharedWorldDelta {
	var d SharedWorldDelta
	d.NextEntity, d.Created, d.Destroyed = next.NextEntity, next.Created, next.Destroyed
	d.Positions = diffStore(base.Positions, next.Positions)
	d.Glyph = diffStore(base.Glyph, next.Glyph)
	d.Sigil = diffStore(base.Sigil, next.Sigil)
	d.Nugget = diffStore(base.Nugget, next.Nugget)
	d.Cursor = diffStore(base.Cursor, next.Cursor)
	d.Protection = diffStore(base.Protection, next.Protection)
	d.Kinetic = diffStore(base.Kinetic, next.Kinetic)
	d.Wall = diffStore(base.Wall, next.Wall)
	d.Loot = diffStore(base.Loot, next.Loot)
	d.Gateway = diffStore(base.Gateway, next.Gateway)
	d.Energy = diffStore(base.Energy, next.Energy)
	d.Heat = diffStore(base.Heat, next.Heat)
	d.Shield = diffStore(base.Shield, next.Shield)
	d.Boost = diffStore(base.Boost, next.Boost)
	d.Weapon = diffStore(base.Weapon, next.Weapon)
	d.Orb = diffStore(base.Orb, next.Orb)
	d.Ping = diffStore(base.Ping, next.Ping)
	d.CursorView = diffStore(base.CursorView, next.CursorView)
	d.Particle = diffStore(base.Particle, next.Particle)
	d.Cleaner = diffStore(base.Cleaner, next.Cleaner)
	d.Dust = diffStore(base.Dust, next.Dust)
	d.Navigation = diffStore(base.Navigation, next.Navigation)
	d.Combat = diffStore(base.Combat, next.Combat)
	d.Genotype = diffStore(base.Genotype, next.Genotype)
	d.Lightning = diffStore(base.Lightning, next.Lightning)
	d.Missile = diffStore(base.Missile, next.Missile)
	d.Mount = diffStore(base.Mount, next.Mount)
	d.Ray = diffStore(base.Ray, next.Ray)
	d.Spirit = diffStore(base.Spirit, next.Spirit)
	d.Materialize = diffStore(base.Materialize, next.Materialize)
	d.Target = diffStore(base.Target, next.Target)
	d.TargetAnchor = diffStore(base.TargetAnchor, next.TargetAnchor)
	d.Drain = diffStore(base.Drain, next.Drain)
	d.Quasar = diffStore(base.Quasar, next.Quasar)
	d.Swarm = diffStore(base.Swarm, next.Swarm)
	d.Storm = diffStore(base.Storm, next.Storm)
	d.StormCircle = diffStore(base.StormCircle, next.StormCircle)
	d.Bullet = diffStore(base.Bullet, next.Bullet)
	d.Pylon = diffStore(base.Pylon, next.Pylon)
	d.Snake = diffStore(base.Snake, next.Snake)
	d.SnakeHead = diffStore(base.SnakeHead, next.SnakeHead)
	d.SnakeBody = diffStore(base.SnakeBody, next.SnakeBody)
	d.SnakeMember = diffStore(base.SnakeMember, next.SnakeMember)
	d.Eye = diffStore(base.Eye, next.Eye)
	d.Tower = diffStore(base.Tower, next.Tower)
	d.Kraken = diffStore(base.Kraken, next.Kraken)
	d.Header = diffStore(base.Header, next.Header)
	d.Member = diffStore(base.Member, next.Member)
	d.Flash = diffStore(base.Flash, next.Flash)
	d.Fadeout = diffStore(base.Fadeout, next.Fadeout)
	d.Splash = diffStore(base.Splash, next.Splash)
	d.Marker = diffStore(base.Marker, next.Marker)
	d.Death = diffStore(base.Death, next.Death)
	d.Timer = diffStore(base.Timer, next.Timer)
	return d
}

// ApplySharedWorldDelta reconstructs the world a delta was computed for.
func ApplySharedWorldDelta(base SharedWorldState, d SharedWorldDelta) SharedWorldState {
	var s SharedWorldState
	s.NextEntity, s.Created, s.Destroyed = d.NextEntity, d.Created, d.Destroyed
	s.Positions = applyStore(base.Positions, d.Positions)
	s.Glyph = applyStore(base.Glyph, d.Glyph)
	s.Sigil = applyStore(base.Sigil, d.Sigil)
	s.Nugget = applyStore(base.Nugget, d.Nugget)
	s.Cursor = applyStore(base.Cursor, d.Cursor)
	s.Protection = applyStore(base.Protection, d.Protection)
	s.Kinetic = applyStore(base.Kinetic, d.Kinetic)
	s.Wall = applyStore(base.Wall, d.Wall)
	s.Loot = applyStore(base.Loot, d.Loot)
	s.Gateway = applyStore(base.Gateway, d.Gateway)
	s.Energy = applyStore(base.Energy, d.Energy)
	s.Heat = applyStore(base.Heat, d.Heat)
	s.Shield = applyStore(base.Shield, d.Shield)
	s.Boost = applyStore(base.Boost, d.Boost)
	s.Weapon = applyStore(base.Weapon, d.Weapon)
	s.Orb = applyStore(base.Orb, d.Orb)
	s.Ping = applyStore(base.Ping, d.Ping)
	s.CursorView = applyStore(base.CursorView, d.CursorView)
	s.Particle = applyStore(base.Particle, d.Particle)
	s.Cleaner = applyStore(base.Cleaner, d.Cleaner)
	s.Dust = applyStore(base.Dust, d.Dust)
	s.Navigation = applyStore(base.Navigation, d.Navigation)
	s.Combat = applyStore(base.Combat, d.Combat)
	s.Genotype = applyStore(base.Genotype, d.Genotype)
	s.Lightning = applyStore(base.Lightning, d.Lightning)
	s.Missile = applyStore(base.Missile, d.Missile)
	s.Mount = applyStore(base.Mount, d.Mount)
	s.Ray = applyStore(base.Ray, d.Ray)
	s.Spirit = applyStore(base.Spirit, d.Spirit)
	s.Materialize = applyStore(base.Materialize, d.Materialize)
	s.Target = applyStore(base.Target, d.Target)
	s.TargetAnchor = applyStore(base.TargetAnchor, d.TargetAnchor)
	s.Drain = applyStore(base.Drain, d.Drain)
	s.Quasar = applyStore(base.Quasar, d.Quasar)
	s.Swarm = applyStore(base.Swarm, d.Swarm)
	s.Storm = applyStore(base.Storm, d.Storm)
	s.StormCircle = applyStore(base.StormCircle, d.StormCircle)
	s.Bullet = applyStore(base.Bullet, d.Bullet)
	s.Pylon = applyStore(base.Pylon, d.Pylon)
	s.Snake = applyStore(base.Snake, d.Snake)
	s.SnakeHead = applyStore(base.SnakeHead, d.SnakeHead)
	s.SnakeBody = applyStore(base.SnakeBody, d.SnakeBody)
	s.SnakeMember = applyStore(base.SnakeMember, d.SnakeMember)
	s.Eye = applyStore(base.Eye, d.Eye)
	s.Tower = applyStore(base.Tower, d.Tower)
	s.Kraken = applyStore(base.Kraken, d.Kraken)
	s.Header = applyStore(base.Header, d.Header)
	s.Member = applyStore(base.Member, d.Member)
	s.Flash = applyStore(base.Flash, d.Flash)
	s.Fadeout = applyStore(base.Fadeout, d.Fadeout)
	s.Splash = applyStore(base.Splash, d.Splash)
	s.Marker = applyStore(base.Marker, d.Marker)
	s.Death = applyStore(base.Death, d.Death)
	s.Timer = applyStore(base.Timer, d.Timer)
	return s
}

// DeltaEntries counts the component cells a delta moves, which is what a
// correction's size is reported in.
func (d SharedWorldDelta) DeltaEntries() int {
	n := d.Positions.Entries()
	n += d.Glyph.Entries()
	n += d.Sigil.Entries()
	n += d.Nugget.Entries()
	n += d.Cursor.Entries()
	n += d.Protection.Entries()
	n += d.Kinetic.Entries()
	n += d.Wall.Entries()
	n += d.Loot.Entries()
	n += d.Gateway.Entries()
	n += d.Energy.Entries()
	n += d.Heat.Entries()
	n += d.Shield.Entries()
	n += d.Boost.Entries()
	n += d.Weapon.Entries()
	n += d.Orb.Entries()
	n += d.Ping.Entries()
	n += d.CursorView.Entries()
	n += d.Particle.Entries()
	n += d.Cleaner.Entries()
	n += d.Dust.Entries()
	n += d.Navigation.Entries()
	n += d.Combat.Entries()
	n += d.Genotype.Entries()
	n += d.Lightning.Entries()
	n += d.Missile.Entries()
	n += d.Mount.Entries()
	n += d.Ray.Entries()
	n += d.Spirit.Entries()
	n += d.Materialize.Entries()
	n += d.Target.Entries()
	n += d.TargetAnchor.Entries()
	n += d.Drain.Entries()
	n += d.Quasar.Entries()
	n += d.Swarm.Entries()
	n += d.Storm.Entries()
	n += d.StormCircle.Entries()
	n += d.Bullet.Entries()
	n += d.Pylon.Entries()
	n += d.Snake.Entries()
	n += d.SnakeHead.Entries()
	n += d.SnakeBody.Entries()
	n += d.SnakeMember.Entries()
	n += d.Eye.Entries()
	n += d.Tower.Entries()
	n += d.Kraken.Entries()
	n += d.Header.Entries()
	n += d.Member.Entries()
	n += d.Flash.Entries()
	n += d.Fadeout.Entries()
	n += d.Splash.Entries()
	n += d.Marker.Entries()
	n += d.Death.Entries()
	n += d.Timer.Entries()
	return n
}

// SharedWorldDifference measures how far apart two readings of the shared world
// are. On a guest that is the correction magnitude: the distance between what it
// predicted and what the host is telling it.
func SharedWorldDifference(a, b SharedWorldState) WorldDifference {
	touched := make(map[core.Entity]struct{}, 64)
	var w WorldDifference
	w.Entries = countStoreDifference(a.Positions, b.Positions, touched)
	w.Entries += countStoreDifference(a.Glyph, b.Glyph, touched)
	w.Entries += countStoreDifference(a.Sigil, b.Sigil, touched)
	w.Entries += countStoreDifference(a.Nugget, b.Nugget, touched)
	w.Entries += countStoreDifference(a.Cursor, b.Cursor, touched)
	w.Entries += countStoreDifference(a.Protection, b.Protection, touched)
	w.Entries += countStoreDifference(a.Kinetic, b.Kinetic, touched)
	w.Entries += countStoreDifference(a.Wall, b.Wall, touched)
	w.Entries += countStoreDifference(a.Loot, b.Loot, touched)
	w.Entries += countStoreDifference(a.Gateway, b.Gateway, touched)
	w.Entries += countStoreDifference(a.Energy, b.Energy, touched)
	w.Entries += countStoreDifference(a.Heat, b.Heat, touched)
	w.Entries += countStoreDifference(a.Shield, b.Shield, touched)
	w.Entries += countStoreDifference(a.Boost, b.Boost, touched)
	w.Entries += countStoreDifference(a.Weapon, b.Weapon, touched)
	w.Entries += countStoreDifference(a.Orb, b.Orb, touched)
	w.Entries += countStoreDifference(a.Ping, b.Ping, touched)
	w.Entries += countStoreDifference(a.CursorView, b.CursorView, touched)
	w.Entries += countStoreDifference(a.Particle, b.Particle, touched)
	w.Entries += countStoreDifference(a.Cleaner, b.Cleaner, touched)
	w.Entries += countStoreDifference(a.Dust, b.Dust, touched)
	w.Entries += countStoreDifference(a.Navigation, b.Navigation, touched)
	w.Entries += countStoreDifference(a.Combat, b.Combat, touched)
	w.Entries += countStoreDifference(a.Genotype, b.Genotype, touched)
	w.Entries += countStoreDifference(a.Lightning, b.Lightning, touched)
	w.Entries += countStoreDifference(a.Missile, b.Missile, touched)
	w.Entries += countStoreDifference(a.Mount, b.Mount, touched)
	w.Entries += countStoreDifference(a.Ray, b.Ray, touched)
	w.Entries += countStoreDifference(a.Spirit, b.Spirit, touched)
	w.Entries += countStoreDifference(a.Materialize, b.Materialize, touched)
	w.Entries += countStoreDifference(a.Target, b.Target, touched)
	w.Entries += countStoreDifference(a.TargetAnchor, b.TargetAnchor, touched)
	w.Entries += countStoreDifference(a.Drain, b.Drain, touched)
	w.Entries += countStoreDifference(a.Quasar, b.Quasar, touched)
	w.Entries += countStoreDifference(a.Swarm, b.Swarm, touched)
	w.Entries += countStoreDifference(a.Storm, b.Storm, touched)
	w.Entries += countStoreDifference(a.StormCircle, b.StormCircle, touched)
	w.Entries += countStoreDifference(a.Bullet, b.Bullet, touched)
	w.Entries += countStoreDifference(a.Pylon, b.Pylon, touched)
	w.Entries += countStoreDifference(a.Snake, b.Snake, touched)
	w.Entries += countStoreDifference(a.SnakeHead, b.SnakeHead, touched)
	w.Entries += countStoreDifference(a.SnakeBody, b.SnakeBody, touched)
	w.Entries += countStoreDifference(a.SnakeMember, b.SnakeMember, touched)
	w.Entries += countStoreDifference(a.Eye, b.Eye, touched)
	w.Entries += countStoreDifference(a.Tower, b.Tower, touched)
	w.Entries += countStoreDifference(a.Kraken, b.Kraken, touched)
	w.Entries += countStoreDifference(a.Header, b.Header, touched)
	w.Entries += countStoreDifference(a.Member, b.Member, touched)
	w.Entries += countStoreDifference(a.Flash, b.Flash, touched)
	w.Entries += countStoreDifference(a.Fadeout, b.Fadeout, touched)
	w.Entries += countStoreDifference(a.Splash, b.Splash, touched)
	w.Entries += countStoreDifference(a.Marker, b.Marker, touched)
	w.Entries += countStoreDifference(a.Death, b.Death, touched)
	w.Entries += countStoreDifference(a.Timer, b.Timer, touched)
	w.Entities = len(touched)
	w.CellShift = positionShift(a.Positions, b.Positions)
	return w
}

// ReconcileSharedWorld brings this world's shared half to s by writing what
// differs instead of replacing everything.
//
// It exists because a correction is not a join. InstallSharedWorld clears every
// shared entity out of all fifty-two stores and re-inserts the capture, which is
// the right shape once, for a participant that has no world yet, and the wrong
// shape two to five times a second for one that has a world nearly identical to
// the capture already. The teardown is the expensive half — every removal is a
// mask edit, a dense swap-back in each store it touches, and a spatial index
// eviction — and a correction throws away and rebuilds state that never moved.
//
// What this writes is bounded by the *correction magnitude* rather than by the
// world size: the entities the authority no longer has, the components an entity
// no longer carries, and every entry's value. What it still scans is the world,
// because finding the first two means looking.
//
// The result is the same world InstallSharedWorld would leave, with one difference
// that is deliberate: the dense store order is whatever the live world already had
// rather than the sender's. Nothing compares it — the shared digest sorts, and the
// compared surface is keyed — and preserving it is what keeps the spatial index
// from churning. TestReconcileMatchesAFullInstall is what holds the equality.
//
// Caller MUST hold updateMutex.
func (w *World) ReconcileSharedWorld(s SharedWorldState) {
	target := make(map[core.Entity]struct{}, len(s.Positions))
	for _, en := range s.Positions {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Glyph {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Sigil {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Nugget {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Cursor {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Protection {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Kinetic {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Wall {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Loot {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Gateway {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Energy {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Heat {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Shield {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Boost {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Weapon {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Orb {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Ping {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.CursorView {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Particle {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Cleaner {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Dust {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Navigation {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Combat {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Genotype {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Lightning {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Missile {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Mount {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Ray {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Spirit {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Materialize {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Target {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.TargetAnchor {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Drain {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Quasar {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Swarm {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Storm {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.StormCircle {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Bullet {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Pylon {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Snake {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.SnakeHead {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.SnakeBody {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.SnakeMember {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Eye {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Tower {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Kraken {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Header {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Member {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Flash {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Fadeout {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Splash {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Marker {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Death {
		target[en.Entity] = struct{}{}
	}
	for _, en := range s.Timer {
		target[en.Entity] = struct{}{}
	}

	// Entities the authority no longer holds leave whole, so no zero-component
	// mask entry is left behind for clearSharedEntities to find later.
	gone := make([]core.Entity, 0, 8)
	for e := range w.componentMask {
		if e.Domain() != core.DomainShared {
			continue
		}
		if _, ok := target[e]; !ok {
			gone = append(gone, e)
		}
	}
	slices.Sort(gone)
	for _, e := range gone {
		w.removeEntity(e)
	}

	reconcilePositions(w.Positions, s.Positions)
	reconcileStore(w.Components.Glyph, s.Glyph)
	reconcileStore(w.Components.Sigil, s.Sigil)
	reconcileStore(w.Components.Nugget, s.Nugget)
	reconcileStore(w.Components.Cursor, s.Cursor)
	reconcileStore(w.Components.Protection, s.Protection)
	reconcileStore(w.Components.Kinetic, s.Kinetic)
	reconcileStore(w.Components.Wall, s.Wall)
	reconcileStore(w.Components.Loot, s.Loot)
	reconcileStore(w.Components.Gateway, s.Gateway)
	reconcileStore(w.Components.Energy, s.Energy)
	reconcileStore(w.Components.Heat, s.Heat)
	reconcileStore(w.Components.Shield, s.Shield)
	reconcileStore(w.Components.Boost, s.Boost)
	reconcileStore(w.Components.Weapon, s.Weapon)
	reconcileStore(w.Components.Orb, s.Orb)
	reconcileStore(w.Components.Ping, s.Ping)
	reconcileStore(w.Components.CursorView, s.CursorView)
	reconcileStore(w.Components.Particle, s.Particle)
	reconcileStore(w.Components.Cleaner, s.Cleaner)
	reconcileStore(w.Components.Dust, s.Dust)
	reconcileStore(w.Components.Navigation, s.Navigation)
	reconcileStore(w.Components.Combat, s.Combat)
	reconcileStore(w.Components.Genotype, s.Genotype)
	reconcileStore(w.Components.Lightning, s.Lightning)
	reconcileStore(w.Components.Missile, s.Missile)
	reconcileStore(w.Components.Mount, s.Mount)
	reconcileStore(w.Components.Ray, s.Ray)
	reconcileStore(w.Components.Spirit, s.Spirit)
	reconcileStore(w.Components.Materialize, s.Materialize)
	reconcileStore(w.Components.Target, s.Target)
	reconcileStore(w.Components.TargetAnchor, s.TargetAnchor)
	reconcileStore(w.Components.Drain, s.Drain)
	reconcileStore(w.Components.Quasar, s.Quasar)
	reconcileStore(w.Components.Swarm, s.Swarm)
	reconcileStore(w.Components.Storm, s.Storm)
	reconcileStore(w.Components.StormCircle, s.StormCircle)
	reconcileStore(w.Components.Bullet, s.Bullet)
	reconcileStore(w.Components.Pylon, s.Pylon)
	reconcileStore(w.Components.Snake, s.Snake)
	reconcileStore(w.Components.SnakeHead, s.SnakeHead)
	reconcileStore(w.Components.SnakeBody, s.SnakeBody)
	reconcileStore(w.Components.SnakeMember, s.SnakeMember)
	reconcileStore(w.Components.Eye, s.Eye)
	reconcileStore(w.Components.Tower, s.Tower)
	reconcileStore(w.Components.Kraken, s.Kraken)
	reconcileStore(w.Components.Header, s.Header)
	reconcileStore(w.Components.Member, s.Member)
	reconcileStore(w.Components.Flash, s.Flash)
	reconcileStore(w.Components.Fadeout, s.Fadeout)
	reconcileStore(w.Components.Splash, s.Splash)
	reconcileStore(w.Components.Marker, s.Marker)
	reconcileStore(w.Components.Death, s.Death)
	reconcileStore(w.Components.Timer, s.Timer)

	if s.NextEntity > 0 {
		w.nextEntityID[core.DomainShared] = s.NextEntity
	}
	w.createdCount[core.DomainShared].Store(s.Created)
	w.destroyedCount[core.DomainShared].Store(s.Destroyed)
	w.Positions.PublishTelemetry()
}

// clearSharedEntities removes every shared entity from every store, so an install
// replaces the shared world rather than merging into it. Merging would leave
// entities this instance had derived on its own beside the capture's, which is
// the divergence an install exists to end.
//
// Caller MUST hold updateMutex.
func (w *World) clearSharedEntities() {
	shared := make([]core.Entity, 0, len(w.componentMask))
	for e := range w.componentMask {
		if e.Domain() == core.DomainShared {
			shared = append(shared, e)
		}
	}
	// Sorted before removal: the stores are dense with swap-back removal, so the
	// order entities leave in decides where the player entities that stay end up.
	// That layout is not compared, but an install must not be one of the places a
	// map's iteration order reaches the world.
	slices.Sort(shared)
	for _, e := range shared {
		w.removeEntity(e)
	}
}
