// Code generated by gen-manifest; DO NOT EDIT.

package engine

import (
	"encoding/json"
	"fmt"
	"slices"

	"github.com/lixenwraith/vif/internal/core"
)

// StoreRow is one component cell in the manifest's canonical form: the entity it
// belongs to and the exact bytes its value marshals to. The bytes are the hashed
// content and the repaired content both, so a row that hashes equal decodes equal.
type StoreRow struct {
	Entity core.Entity     `json:"e"`
	Value  json.RawMessage `json:"v"`
}

// SharedWorldStoreNames are the wire-stable section ids of the capture's component
// stores, in a fixed order. The name is what a shard names, so it may not change
// without a manifest version change.
var SharedWorldStoreNames = []string{
	"positions",
	"glyph",
	"sigil",
	"nugget",
	"cursor",
	"protection",
	"kinetic",
	"wall",
	"loot",
	"gateway",
	"energy",
	"heat",
	"shield",
	"boost",
	"weapon",
	"orb",
	"ping",
	"cursorview",
	"particle",
	"cleaner",
	"dust",
	"navigation",
	"combat",
	"genotype",
	"lightning",
	"missile",
	"mount",
	"beam",
	"spirit",
	"materialize",
	"target",
	"targetanchor",
	"drain",
	"quasar",
	"swarm",
	"storm",
	"stormcircle",
	"bullet",
	"pylon",
	"snake",
	"snakehead",
	"snakebody",
	"snakemember",
	"eye",
	"tower",
	"kraken",
	"header",
	"member",
	"flash",
	"fadeout",
	"splash",
	"marker",
	"death",
	"timer",
}

// SharedWorldStoreCount is how many component stores a capture carries.
var SharedWorldStoreCount = len(SharedWorldStoreNames)

// SharedWorldStoreRows appends store i's cells to dst in entity-ascending order.
//
// Marshalling per cell rather than per store is what makes a page independently
// hashable and independently repairable; it runs on the correction goroutine,
// outside the world lock, on a capture that has already been taken.
func SharedWorldStoreRows(s *SharedWorldState, i int, dst []StoreRow) ([]StoreRow, error) {
	switch i {
	case 0:
		return appendStoreRows(dst, s.Positions)
	case 1:
		return appendStoreRows(dst, s.Glyph)
	case 2:
		return appendStoreRows(dst, s.Sigil)
	case 3:
		return appendStoreRows(dst, s.Nugget)
	case 4:
		return appendStoreRows(dst, s.Cursor)
	case 5:
		return appendStoreRows(dst, s.Protection)
	case 6:
		return appendStoreRows(dst, s.Kinetic)
	case 7:
		return appendStoreRows(dst, s.Wall)
	case 8:
		return appendStoreRows(dst, s.Loot)
	case 9:
		return appendStoreRows(dst, s.Gateway)
	case 10:
		return appendStoreRows(dst, s.Energy)
	case 11:
		return appendStoreRows(dst, s.Heat)
	case 12:
		return appendStoreRows(dst, s.Shield)
	case 13:
		return appendStoreRows(dst, s.Boost)
	case 14:
		return appendStoreRows(dst, s.Weapon)
	case 15:
		return appendStoreRows(dst, s.Orb)
	case 16:
		return appendStoreRows(dst, s.Ping)
	case 17:
		return appendStoreRows(dst, s.CursorView)
	case 18:
		return appendStoreRows(dst, s.Particle)
	case 19:
		return appendStoreRows(dst, s.Cleaner)
	case 20:
		return appendStoreRows(dst, s.Dust)
	case 21:
		return appendStoreRows(dst, s.Navigation)
	case 22:
		return appendStoreRows(dst, s.Combat)
	case 23:
		return appendStoreRows(dst, s.Genotype)
	case 24:
		return appendStoreRows(dst, s.Lightning)
	case 25:
		return appendStoreRows(dst, s.Missile)
	case 26:
		return appendStoreRows(dst, s.Mount)
	case 27:
		return appendStoreRows(dst, s.Beam)
	case 28:
		return appendStoreRows(dst, s.Spirit)
	case 29:
		return appendStoreRows(dst, s.Materialize)
	case 30:
		return appendStoreRows(dst, s.Target)
	case 31:
		return appendStoreRows(dst, s.TargetAnchor)
	case 32:
		return appendStoreRows(dst, s.Drain)
	case 33:
		return appendStoreRows(dst, s.Quasar)
	case 34:
		return appendStoreRows(dst, s.Swarm)
	case 35:
		return appendStoreRows(dst, s.Storm)
	case 36:
		return appendStoreRows(dst, s.StormCircle)
	case 37:
		return appendStoreRows(dst, s.Bullet)
	case 38:
		return appendStoreRows(dst, s.Pylon)
	case 39:
		return appendStoreRows(dst, s.Snake)
	case 40:
		return appendStoreRows(dst, s.SnakeHead)
	case 41:
		return appendStoreRows(dst, s.SnakeBody)
	case 42:
		return appendStoreRows(dst, s.SnakeMember)
	case 43:
		return appendStoreRows(dst, s.Eye)
	case 44:
		return appendStoreRows(dst, s.Tower)
	case 45:
		return appendStoreRows(dst, s.Kraken)
	case 46:
		return appendStoreRows(dst, s.Header)
	case 47:
		return appendStoreRows(dst, s.Member)
	case 48:
		return appendStoreRows(dst, s.Flash)
	case 49:
		return appendStoreRows(dst, s.Fadeout)
	case 50:
		return appendStoreRows(dst, s.Splash)
	case 51:
		return appendStoreRows(dst, s.Marker)
	case 52:
		return appendStoreRows(dst, s.Death)
	case 53:
		return appendStoreRows(dst, s.Timer)
	}
	return nil, fmt.Errorf("capture holds no store %d", i)
}

// SharedWorldApplyStoreRows replaces every cell of store i the page owns with rows.
//
// owns names the page's entities rather than the rows': a page whose content the
// authority no longer holds is repaired by an empty row set, and a receiver that
// only overwrote what arrived would keep a cell the authority had dropped.
func SharedWorldApplyStoreRows(s *SharedWorldState, i int, owns func(core.Entity) bool, rows []StoreRow) error {
	switch i {
	case 0:
		out, err := applyStoreRows(s.Positions, owns, rows)
		if err != nil {
			return err
		}
		s.Positions = out
		return nil
	case 1:
		out, err := applyStoreRows(s.Glyph, owns, rows)
		if err != nil {
			return err
		}
		s.Glyph = out
		return nil
	case 2:
		out, err := applyStoreRows(s.Sigil, owns, rows)
		if err != nil {
			return err
		}
		s.Sigil = out
		return nil
	case 3:
		out, err := applyStoreRows(s.Nugget, owns, rows)
		if err != nil {
			return err
		}
		s.Nugget = out
		return nil
	case 4:
		out, err := applyStoreRows(s.Cursor, owns, rows)
		if err != nil {
			return err
		}
		s.Cursor = out
		return nil
	case 5:
		out, err := applyStoreRows(s.Protection, owns, rows)
		if err != nil {
			return err
		}
		s.Protection = out
		return nil
	case 6:
		out, err := applyStoreRows(s.Kinetic, owns, rows)
		if err != nil {
			return err
		}
		s.Kinetic = out
		return nil
	case 7:
		out, err := applyStoreRows(s.Wall, owns, rows)
		if err != nil {
			return err
		}
		s.Wall = out
		return nil
	case 8:
		out, err := applyStoreRows(s.Loot, owns, rows)
		if err != nil {
			return err
		}
		s.Loot = out
		return nil
	case 9:
		out, err := applyStoreRows(s.Gateway, owns, rows)
		if err != nil {
			return err
		}
		s.Gateway = out
		return nil
	case 10:
		out, err := applyStoreRows(s.Energy, owns, rows)
		if err != nil {
			return err
		}
		s.Energy = out
		return nil
	case 11:
		out, err := applyStoreRows(s.Heat, owns, rows)
		if err != nil {
			return err
		}
		s.Heat = out
		return nil
	case 12:
		out, err := applyStoreRows(s.Shield, owns, rows)
		if err != nil {
			return err
		}
		s.Shield = out
		return nil
	case 13:
		out, err := applyStoreRows(s.Boost, owns, rows)
		if err != nil {
			return err
		}
		s.Boost = out
		return nil
	case 14:
		out, err := applyStoreRows(s.Weapon, owns, rows)
		if err != nil {
			return err
		}
		s.Weapon = out
		return nil
	case 15:
		out, err := applyStoreRows(s.Orb, owns, rows)
		if err != nil {
			return err
		}
		s.Orb = out
		return nil
	case 16:
		out, err := applyStoreRows(s.Ping, owns, rows)
		if err != nil {
			return err
		}
		s.Ping = out
		return nil
	case 17:
		out, err := applyStoreRows(s.CursorView, owns, rows)
		if err != nil {
			return err
		}
		s.CursorView = out
		return nil
	case 18:
		out, err := applyStoreRows(s.Particle, owns, rows)
		if err != nil {
			return err
		}
		s.Particle = out
		return nil
	case 19:
		out, err := applyStoreRows(s.Cleaner, owns, rows)
		if err != nil {
			return err
		}
		s.Cleaner = out
		return nil
	case 20:
		out, err := applyStoreRows(s.Dust, owns, rows)
		if err != nil {
			return err
		}
		s.Dust = out
		return nil
	case 21:
		out, err := applyStoreRows(s.Navigation, owns, rows)
		if err != nil {
			return err
		}
		s.Navigation = out
		return nil
	case 22:
		out, err := applyStoreRows(s.Combat, owns, rows)
		if err != nil {
			return err
		}
		s.Combat = out
		return nil
	case 23:
		out, err := applyStoreRows(s.Genotype, owns, rows)
		if err != nil {
			return err
		}
		s.Genotype = out
		return nil
	case 24:
		out, err := applyStoreRows(s.Lightning, owns, rows)
		if err != nil {
			return err
		}
		s.Lightning = out
		return nil
	case 25:
		out, err := applyStoreRows(s.Missile, owns, rows)
		if err != nil {
			return err
		}
		s.Missile = out
		return nil
	case 26:
		out, err := applyStoreRows(s.Mount, owns, rows)
		if err != nil {
			return err
		}
		s.Mount = out
		return nil
	case 27:
		out, err := applyStoreRows(s.Beam, owns, rows)
		if err != nil {
			return err
		}
		s.Beam = out
		return nil
	case 28:
		out, err := applyStoreRows(s.Spirit, owns, rows)
		if err != nil {
			return err
		}
		s.Spirit = out
		return nil
	case 29:
		out, err := applyStoreRows(s.Materialize, owns, rows)
		if err != nil {
			return err
		}
		s.Materialize = out
		return nil
	case 30:
		out, err := applyStoreRows(s.Target, owns, rows)
		if err != nil {
			return err
		}
		s.Target = out
		return nil
	case 31:
		out, err := applyStoreRows(s.TargetAnchor, owns, rows)
		if err != nil {
			return err
		}
		s.TargetAnchor = out
		return nil
	case 32:
		out, err := applyStoreRows(s.Drain, owns, rows)
		if err != nil {
			return err
		}
		s.Drain = out
		return nil
	case 33:
		out, err := applyStoreRows(s.Quasar, owns, rows)
		if err != nil {
			return err
		}
		s.Quasar = out
		return nil
	case 34:
		out, err := applyStoreRows(s.Swarm, owns, rows)
		if err != nil {
			return err
		}
		s.Swarm = out
		return nil
	case 35:
		out, err := applyStoreRows(s.Storm, owns, rows)
		if err != nil {
			return err
		}
		s.Storm = out
		return nil
	case 36:
		out, err := applyStoreRows(s.StormCircle, owns, rows)
		if err != nil {
			return err
		}
		s.StormCircle = out
		return nil
	case 37:
		out, err := applyStoreRows(s.Bullet, owns, rows)
		if err != nil {
			return err
		}
		s.Bullet = out
		return nil
	case 38:
		out, err := applyStoreRows(s.Pylon, owns, rows)
		if err != nil {
			return err
		}
		s.Pylon = out
		return nil
	case 39:
		out, err := applyStoreRows(s.Snake, owns, rows)
		if err != nil {
			return err
		}
		s.Snake = out
		return nil
	case 40:
		out, err := applyStoreRows(s.SnakeHead, owns, rows)
		if err != nil {
			return err
		}
		s.SnakeHead = out
		return nil
	case 41:
		out, err := applyStoreRows(s.SnakeBody, owns, rows)
		if err != nil {
			return err
		}
		s.SnakeBody = out
		return nil
	case 42:
		out, err := applyStoreRows(s.SnakeMember, owns, rows)
		if err != nil {
			return err
		}
		s.SnakeMember = out
		return nil
	case 43:
		out, err := applyStoreRows(s.Eye, owns, rows)
		if err != nil {
			return err
		}
		s.Eye = out
		return nil
	case 44:
		out, err := applyStoreRows(s.Tower, owns, rows)
		if err != nil {
			return err
		}
		s.Tower = out
		return nil
	case 45:
		out, err := applyStoreRows(s.Kraken, owns, rows)
		if err != nil {
			return err
		}
		s.Kraken = out
		return nil
	case 46:
		out, err := applyStoreRows(s.Header, owns, rows)
		if err != nil {
			return err
		}
		s.Header = out
		return nil
	case 47:
		out, err := applyStoreRows(s.Member, owns, rows)
		if err != nil {
			return err
		}
		s.Member = out
		return nil
	case 48:
		out, err := applyStoreRows(s.Flash, owns, rows)
		if err != nil {
			return err
		}
		s.Flash = out
		return nil
	case 49:
		out, err := applyStoreRows(s.Fadeout, owns, rows)
		if err != nil {
			return err
		}
		s.Fadeout = out
		return nil
	case 50:
		out, err := applyStoreRows(s.Splash, owns, rows)
		if err != nil {
			return err
		}
		s.Splash = out
		return nil
	case 51:
		out, err := applyStoreRows(s.Marker, owns, rows)
		if err != nil {
			return err
		}
		s.Marker = out
		return nil
	case 52:
		out, err := applyStoreRows(s.Death, owns, rows)
		if err != nil {
			return err
		}
		s.Death = out
		return nil
	case 53:
		out, err := applyStoreRows(s.Timer, owns, rows)
		if err != nil {
			return err
		}
		s.Timer = out
		return nil
	}
	return fmt.Errorf("capture holds no store %d", i)
}

// appendStoreRows renders one store's entries in the manifest's canonical order.
func appendStoreRows[T any](dst []StoreRow, entries []StoreEntry[T]) ([]StoreRow, error) {
	start := len(dst)
	for _, en := range entries {
		v, err := json.Marshal(en.Value)
		if err != nil {
			return nil, err
		}
		dst = append(dst, StoreRow{Entity: en.Entity, Value: v})
	}
	rows := dst[start:]
	slices.SortFunc(rows, func(a, b StoreRow) int {
		switch {
		case a.Entity < b.Entity:
			return -1
		case a.Entity > b.Entity:
			return 1
		}
		return 0
	})
	return dst, nil
}

// applyStoreRows rebuilds one store with the page's cells replaced.
//
// The result keeps the entries the page does not own in their existing order and
// appends the page's in canonical order. Store order is not compared and is not in
// the manifest's hashed surface — see SharedWorldStoreRows — so what matters here
// is only that the set and the values are the authority's.
func applyStoreRows[T any](entries []StoreEntry[T], owns func(core.Entity) bool, rows []StoreRow) ([]StoreEntry[T], error) {
	out := make([]StoreEntry[T], 0, len(entries)+len(rows))
	for _, en := range entries {
		if owns(en.Entity) {
			continue
		}
		out = append(out, en)
	}
	for _, row := range rows {
		if !owns(row.Entity) {
			return nil, fmt.Errorf("shard carries entity %d, which its page does not own", uint64(row.Entity))
		}
		var v T
		if err := json.Unmarshal(row.Value, &v); err != nil {
			return nil, err
		}
		out = append(out, StoreEntry[T]{Entity: row.Entity, Value: v})
	}
	return out, nil
}
