// Code generated by gen-manifest; DO NOT EDIT.

package event

// EventTypeCount is the number of declared EventType constants, including EventNone
// Values are contiguous in [0, EventTypeCount)
const EventTypeCount = 182

// InitRegistry populates the registry from the EventType const block in type.go
// Must be called once at startup
func InitRegistry() {
	if registryInit {
		return
	}
	registryInit = true
	RegisterType("EventLevelSetup", EventLevelSetup, &LevelSetupPayload{})
	RegisterType("EventScreenResize", EventScreenResize, &ScreenResizePayload{})
	RegisterType("EventSoundRequest", EventSoundRequest, &SoundRequestPayload{})
	RegisterType("EventSoundMuteToggle", EventSoundMuteToggle, &SoundMuteTogglePayload{})
	RegisterType("EventAudioMuteChanged", EventAudioMuteChanged, &AudioMuteChangedPayload{})
	RegisterType("EventMusicStart", EventMusicStart, &MusicStartPayload{})
	RegisterType("EventMusicStop", EventMusicStop, nil)
	RegisterType("EventBeatPatternRequest", EventBeatPatternRequest, &BeatPatternRequestPayload{})
	RegisterType("EventMelodyNoteRequest", EventMelodyNoteRequest, &MelodyNoteRequestPayload{})
	RegisterType("EventMelodyPatternRequest", EventMelodyPatternRequest, &MelodyPatternRequestPayload{})
	RegisterType("EventMusicIntensityChange", EventMusicIntensityChange, &MusicIntensityPayload{})
	RegisterType("EventMusicTempoChange", EventMusicTempoChange, &MusicTempoPayload{})
	RegisterType("EventMusicSeedRequest", EventMusicSeedRequest, &MusicSeedPayload{})
	RegisterType("EventMusicSwingRequest", EventMusicSwingRequest, &MusicSwingPayload{})
	RegisterType("EventNetworkConnect", EventNetworkConnect, &NetworkConnectPayload{})
	RegisterType("EventNetworkDisconnect", EventNetworkDisconnect, &NetworkDisconnectPayload{})
	RegisterType("EventParticipantJoined", EventParticipantJoined, &ParticipantJoinedPayload{})
	RegisterType("EventParticipantDeparted", EventParticipantDeparted, &ParticipantDepartedPayload{})
	RegisterType("EventPlayoutLead", EventPlayoutLead, &PlayoutLeadPayload{})
	RegisterType("EventCursorStateSync", EventCursorStateSync, &CursorStatePayload{})
	RegisterType("EventSessionState", EventSessionState, &SessionStatePayload{})
	RegisterType("EventGameResetRequest", EventGameResetRequest, &GameResetPayload{})
	RegisterType("EventMetaTelemetryRequest", EventMetaTelemetryRequest, nil)
	RegisterType("EventMetaDebugRequest", EventMetaDebugRequest, nil)
	RegisterType("EventMetaHelpRequest", EventMetaHelpRequest, nil)
	RegisterType("EventMetaAboutRequest", EventMetaAboutRequest, nil)
	RegisterType("EventMetaStatusMessageRequest", EventMetaStatusMessageRequest, &MetaStatusMessagePayload{})
	RegisterType("EventMetaSystemCommandRequest", EventMetaSystemCommandRequest, &MetaSystemCommandPayload{})
	RegisterType("EventGamePauseRequest", EventGamePauseRequest, &GamePausePayload{})
	RegisterType("EventGamePauseChanged", EventGamePauseChanged, &GamePausePayload{})
	RegisterType("EventGameSpeedRequest", EventGameSpeedRequest, &GameSpeedPayload{})
	RegisterType("EventGameSpeedChanged", EventGameSpeedChanged, &GameSpeedPayload{})
	RegisterType("EventGameStepRequest", EventGameStepRequest, &GameStepPayload{})
	RegisterType("EventCycleDamageMultiplierIncrease", EventCycleDamageMultiplierIncrease, nil)
	RegisterType("EventCycleDamageMultiplierReset", EventCycleDamageMultiplierReset, nil)
	RegisterType("EventFSMRegionRequest", EventFSMRegionRequest, &FSMRegionPayload{})
	RegisterType("EventNuggetCollected", EventNuggetCollected, &NuggetCollectedPayload{})
	RegisterType("EventNuggetDestroyed", EventNuggetDestroyed, &NuggetDestroyedPayload{})
	RegisterType("EventNuggetJumpRequest", EventNuggetJumpRequest, &NuggetJumpRequestPayload{})
	RegisterType("EventCleanerDirectionalRequest", EventCleanerDirectionalRequest, &DirectionalCleanerPayload{})
	RegisterType("EventCleanerSweepingRequest", EventCleanerSweepingRequest, &CleanerSweepingRequestPayload{})
	RegisterType("EventGoldSpawnRequest", EventGoldSpawnRequest, nil)
	RegisterType("EventGoldSpawnFailed", EventGoldSpawnFailed, nil)
	RegisterType("EventGoldSpawned", EventGoldSpawned, &GoldSpawnedPayload{})
	RegisterType("EventGoldCompleted", EventGoldCompleted, &GoldCompletionPayload{})
	RegisterType("EventGoldTimeout", EventGoldTimeout, &GoldCompletionPayload{})
	RegisterType("EventGoldDestroyed", EventGoldDestroyed, &GoldCompletionPayload{})
	RegisterType("EventGoldCancel", EventGoldCancel, nil)
	RegisterType("EventGoldJumpRequest", EventGoldJumpRequest, &GoldJumpRequestPayload{})
	RegisterType("EventSplashTimerRequest", EventSplashTimerRequest, &SplashTimerRequestPayload{})
	RegisterType("EventSplashTimerCancel", EventSplashTimerCancel, &SplashTimerCancelPayload{})
	RegisterType("EventEnergyAddRequest", EventEnergyAddRequest, &EnergyAddPayload{})
	RegisterType("EventEnergySetRequest", EventEnergySetRequest, &EnergySetPayload{})
	RegisterType("EventEnergyCrossedZero", EventEnergyCrossedZero, &EnergyCrossedZeroPayload{})
	RegisterType("EventEnergyGlyphConsumed", EventEnergyGlyphConsumed, &EnergyGlyphConsumedPayload{})
	RegisterType("EventEnergyBlinkStart", EventEnergyBlinkStart, &EnergyBlinkPayload{})
	RegisterType("EventEnergyBlinkStop", EventEnergyBlinkStop, &EnergyBlinkStopPayload{})
	RegisterType("EventShieldActivate", EventShieldActivate, &ShieldActivatePayload{})
	RegisterType("EventShieldDeactivate", EventShieldDeactivate, &ShieldDeactivatePayload{})
	RegisterType("EventShieldDrainRequest", EventShieldDrainRequest, &ShieldDrainRequestPayload{})
	RegisterType("EventWeaponAddRequest", EventWeaponAddRequest, &WeaponAddRequestPayload{})
	RegisterType("EventWeaponFireRequest", EventWeaponFireRequest, &WeaponFireRequestPayload{})
	RegisterType("EventFireSpecialRequest", EventFireSpecialRequest, &FireSpecialRequestPayload{})
	RegisterType("EventMountRequest", EventMountRequest, &MountRequestPayload{})
	RegisterType("EventHeatAddRequest", EventHeatAddRequest, &HeatAddRequestPayload{})
	RegisterType("EventHeatSetRequest", EventHeatSetRequest, &HeatSetRequestPayload{})
	RegisterType("EventHeatSpendRequest", EventHeatSpendRequest, &HeatSpendRequestPayload{})
	RegisterType("EventHeatBurst", EventHeatBurst, &HeatBurstPayload{})
	RegisterType("EventBoostActivate", EventBoostActivate, &BoostActivatePayload{})
	RegisterType("EventBoostDeactivate", EventBoostDeactivate, &BoostDeactivatePayload{})
	RegisterType("EventBoostExtend", EventBoostExtend, &BoostExtendPayload{})
	RegisterType("EventBoostReward", EventBoostReward, &BoostRewardPayload{})
	RegisterType("EventCharacterTyped", EventCharacterTyped, &CharacterTypedPayload{})
	RegisterType("EventDeleteRequest", EventDeleteRequest, &DeleteRequestPayload{})
	RegisterType("EventPingGridRequest", EventPingGridRequest, &PingGridRequestPayload{})
	RegisterType("EventMaterializeRequest", EventMaterializeRequest, &MaterializeRequestPayload{})
	RegisterType("EventMaterializeComplete", EventMaterializeComplete, &MaterializeCompletedPayload{})
	RegisterType("EventMaterializeAreaRequest", EventMaterializeAreaRequest, &MaterializeAreaRequestPayload{})
	RegisterType("EventFlashSpawnOneRequest", EventFlashSpawnOneRequest, &FlashRequestPayload{})
	RegisterType("EventFlashSpawnBatchRequest", EventFlashSpawnBatchRequest, nil)
	RegisterType("EventExplosionRequest", EventExplosionRequest, &ExplosionRequestPayload{})
	RegisterType("EventExplosionBatchRequest", EventExplosionBatchRequest, &ExplosionBatchRequestPayload{})
	RegisterType("EventExplosionVisualRequest", EventExplosionVisualRequest, &ExplosionVisualRequestPayload{})
	RegisterType("EventExplosionVisualBatchRequest", EventExplosionVisualBatchRequest, &ExplosionVisualBatchRequestPayload{})
	RegisterType("EventPulseVisualRequest", EventPulseVisualRequest, &PulseVisualRequestPayload{})
	RegisterType("EventDustSpawnOneRequest", EventDustSpawnOneRequest, &DustSpawnOneRequestPayload{})
	RegisterType("EventDustSpawnBatchRequest", EventDustSpawnBatchRequest, nil)
	RegisterType("EventDustAllRequest", EventDustAllRequest, nil)
	RegisterType("EventParticleSpawnOne", EventParticleSpawnOne, &ParticleSpawnPayload{})
	RegisterType("EventParticleSpawnBatch", EventParticleSpawnBatch, nil)
	RegisterType("EventParticleWave", EventParticleWave, &ParticleWavePayload{})
	RegisterType("EventDeathBatch", EventDeathBatch, &DeathRequestPayload{})
	RegisterType("EventTimerStart", EventTimerStart, &TimerStartPayload{})
	RegisterType("EventCompositeMemberDestroyed", EventCompositeMemberDestroyed, &CompositeMemberDestroyedPayload{})
	RegisterType("EventCompositeIntegrityBreach", EventCompositeIntegrityBreach, &CompositeIntegrityBreachPayload{})
	RegisterType("EventCompositeDestroyRequest", EventCompositeDestroyRequest, &CompositeDestroyRequestPayload{})
	RegisterType("EventCursorSpawnRequest", EventCursorSpawnRequest, &CursorSpawnRequestPayload{})
	RegisterType("EventCursorSpawned", EventCursorSpawned, &CursorSpawnedPayload{})
	RegisterType("EventCursorSpawnFailed", EventCursorSpawnFailed, nil)
	RegisterType("EventCursorArmRequest", EventCursorArmRequest, &CursorArmRequestPayload{})
	RegisterType("EventCursorDespawnRequest", EventCursorDespawnRequest, &CursorDespawnRequestPayload{})
	RegisterType("EventCursorDespawned", EventCursorDespawned, &CursorDespawnedPayload{})
	RegisterType("EventCursorMoveRequest", EventCursorMoveRequest, &CursorMoveRequestPayload{})
	RegisterType("EventCursorMoved", EventCursorMoved, &CursorMovedPayload{})
	RegisterType("EventCursorPredicted", EventCursorPredicted, &CursorMoveRequestPayload{})
	RegisterType("EventCursorDefeatState", EventCursorDefeatState, &CursorDefeatStatePayload{})
	RegisterType("EventCursorSetLocalRequest", EventCursorSetLocalRequest, &CursorSetLocalPayload{})
	RegisterType("EventCursorLocalChanged", EventCursorLocalChanged, &CursorSetLocalPayload{})
	RegisterType("EventSpeciesCreated", EventSpeciesCreated, &SpeciesCreatedPayload{})
	RegisterType("EventSpeciesKilled", EventSpeciesKilled, &SpeciesKilledPayload{})
	RegisterType("EventSpeciesKillConfirmed", EventSpeciesKillConfirmed, &SpeciesKilledPayload{})
	RegisterType("EventDrainDefeated", EventDrainDefeated, &DrainDefeatedPayload{})
	RegisterType("EventFuseQuasarRequest", EventFuseQuasarRequest, &FuseQuasarRequestPayload{})
	RegisterType("EventFuseSwarmRequest", EventFuseSwarmRequest, &FuseSwarmRequestPayload{})
	RegisterType("EventDrainPause", EventDrainPause, &CursorScopePayload{})
	RegisterType("EventDrainResume", EventDrainResume, &CursorScopePayload{})
	RegisterType("EventQuasarSpawnRequest", EventQuasarSpawnRequest, &QuasarSpawnRequestPayload{})
	RegisterType("EventQuasarCancelRequest", EventQuasarCancelRequest, nil)
	RegisterType("EventSwarmSpawnRequest", EventSwarmSpawnRequest, &SwarmSpawnRequestPayload{})
	RegisterType("EventSwarmCancelRequest", EventSwarmCancelRequest, nil)
	RegisterType("EventStormSpawnRequest", EventStormSpawnRequest, nil)
	RegisterType("EventStormCancelRequest", EventStormCancelRequest, nil)
	RegisterType("EventKrakenSpawnRequest", EventKrakenSpawnRequest, &KrakenSpawnRequestPayload{})
	RegisterType("EventKrakenSpawnFailed", EventKrakenSpawnFailed, nil)
	RegisterType("EventKrakenCancelRequest", EventKrakenCancelRequest, nil)
	RegisterType("EventWindStart", EventWindStart, &WindStartPayload{})
	RegisterType("EventWindCancel", EventWindCancel, nil)
	RegisterType("EventGrayoutStart", EventGrayoutStart, &CursorScopePayload{})
	RegisterType("EventGrayoutEnd", EventGrayoutEnd, &CursorScopePayload{})
	RegisterType("EventStrobeRequest", EventStrobeRequest, &StrobeRequestPayload{})
	RegisterType("EventSpiritSpawnRequest", EventSpiritSpawnRequest, &SpiritSpawnRequestPayload{})
	RegisterType("EventSpiritDespawnRequest", EventSpiritDespawnRequest, nil)
	RegisterType("EventLightningSpawnRequest", EventLightningSpawnRequest, &LightningSpawnRequestPayload{})
	RegisterType("EventLightningUpdateRequest", EventLightningUpdateRequest, &LightningUpdateRequestPayload{})
	RegisterType("EventLightningDespawnRequest", EventLightningDespawnRequest, &LightningDespawnRequestPayload{})
	RegisterType("EventCombatAttackDirectRequest", EventCombatAttackDirectRequest, &CombatAttackDirectRequestPayload{})
	RegisterType("EventCombatAttackAreaRequest", EventCombatAttackAreaRequest, &CombatAttackAreaRequestPayload{})
	RegisterType("EventCombatAttackAreaCrossingRequest", EventCombatAttackAreaCrossingRequest, &CombatAttackAreaRequestPayload{})
	RegisterType("EventCombatHealRequest", EventCombatHealRequest, &CombatHealRequestPayload{})
	RegisterType("EventLootSpawnRequest", EventLootSpawnRequest, &LootSpawnRequestPayload{})
	RegisterType("EventMissileSpawnRequest", EventMissileSpawnRequest, &MissileSpawnRequestPayload{})
	RegisterType("EventBulletSpawnRequest", EventBulletSpawnRequest, &BulletSpawnRequestPayload{})
	RegisterType("EventMarkerSpawnRequest", EventMarkerSpawnRequest, &MarkerSpawnRequestPayload{})
	RegisterType("EventMotionMarkerShowColored", EventMotionMarkerShowColored, &MotionMarkerShowPayload{})
	RegisterType("EventMotionMarkerClearColored", EventMotionMarkerClearColored, nil)
	RegisterType("EventModeChanged", EventModeChanged, &ModeChangedPayload{})
	RegisterType("EventWallSpawnRequest", EventWallSpawnRequest, &WallSpawnRequestPayload{})
	RegisterType("EventWallBatchSpawnRequest", EventWallBatchSpawnRequest, &WallBatchSpawnRequestPayload{})
	RegisterType("EventWallCompositeSpawnRequest", EventWallCompositeSpawnRequest, &WallCompositeSpawnRequestPayload{})
	RegisterType("EventWallPatternSpawnRequest", EventWallPatternSpawnRequest, &WallPatternSpawnRequestPayload{})
	RegisterType("EventMazeSpawnRequest", EventMazeSpawnRequest, &MazeSpawnRequestPayload{})
	RegisterType("EventWallDespawnRequest", EventWallDespawnRequest, &WallDespawnRequestPayload{})
	RegisterType("EventWallMaskChangeRequest", EventWallMaskChangeRequest, &WallMaskChangeRequestPayload{})
	RegisterType("EventWallPushCheckRequest", EventWallPushCheckRequest, nil)
	RegisterType("EventWallSpawned", EventWallSpawned, &WallSpawnedPayload{})
	RegisterType("EventWallDespawned", EventWallDespawned, &WallDespawnedPayload{})
	RegisterType("EventWallDespawnAll", EventWallDespawnAll, nil)
	RegisterType("EventFadeoutSpawnOne", EventFadeoutSpawnOne, &FadeoutSpawnPayload{})
	RegisterType("EventFadeoutSpawnBatch", EventFadeoutSpawnBatch, nil)
	RegisterType("EventPylonSpawnRequest", EventPylonSpawnRequest, &PylonSpawnRequestPayload{})
	RegisterType("EventPylonSpawnFailed", EventPylonSpawnFailed, nil)
	RegisterType("EventPylonCancelRequest", EventPylonCancelRequest, nil)
	RegisterType("EventSnakeSpawnRequest", EventSnakeSpawnRequest, &SnakeSpawnRequestPayload{})
	RegisterType("EventSnakeCancelRequest", EventSnakeCancelRequest, nil)
	RegisterType("EventTargetGroupUpdate", EventTargetGroupUpdate, &TargetGroupUpdatePayload{})
	RegisterType("EventTargetGroupRemove", EventTargetGroupRemove, &TargetGroupRemovePayload{})
	RegisterType("EventNavigationRegraph", EventNavigationRegraph, nil)
	RegisterType("EventRouteGraphRequest", EventRouteGraphRequest, &RouteGraphRequestPayload{})
	RegisterType("EventRouteGraphComputed", EventRouteGraphComputed, &RouteGraphComputedPayload{})
	RegisterType("EventEyeSpawnRequest", EventEyeSpawnRequest, &EyeSpawnRequestPayload{})
	RegisterType("EventEyeCancelRequest", EventEyeCancelRequest, nil)
	RegisterType("EventTowerSpawnRequest", EventTowerSpawnRequest, &TowerSpawnRequestPayload{})
	RegisterType("EventTowerSpawnFailed", EventTowerSpawnFailed, nil)
	RegisterType("EventTowerCancelRequest", EventTowerCancelRequest, nil)
	RegisterType("EventGatewaySpawnRequest", EventGatewaySpawnRequest, &GatewaySpawnRequestPayload{})
	RegisterType("EventGatewayDespawnRequest", EventGatewayDespawnRequest, &GatewayDespawnRequestPayload{})
	RegisterType("EventGatewayDespawned", EventGatewayDespawned, &GatewayDespawnedPayload{})
	RegisterType("EventGeneticRegisterSpecies", EventGeneticRegisterSpecies, &GeneticRegisterSpeciesPayload{})
	RegisterType("EventGeneticAbandonEval", EventGeneticAbandonEval, &GeneticAbandonEvalPayload{})
	RegisterType("EventDebugFlowToggle", EventDebugFlowToggle, &DebugFlowGroupPayload{})
	RegisterType("EventDebugGraphToggle", EventDebugGraphToggle, &DebugFlowGroupPayload{})

}

// eventClasses is every type's replication class, declared by the "[class]"
// annotation in type.go. Index is the EventType; an unlisted slot is ClassUnset,
// which replicates nothing.
var eventClasses = [EventTypeCount]EventClass{
	EventLevelSetup:                      ClassShared,
	EventScreenResize:                    ClassLocal,
	EventSoundRequest:                    ClassLocal,
	EventSoundMuteToggle:                 ClassLocal,
	EventAudioMuteChanged:                ClassLocal,
	EventMusicStart:                      ClassLocal,
	EventMusicStop:                       ClassLocal,
	EventBeatPatternRequest:              ClassLocal,
	EventMelodyNoteRequest:               ClassLocal,
	EventMelodyPatternRequest:            ClassLocal,
	EventMusicIntensityChange:            ClassLocal,
	EventMusicTempoChange:                ClassLocal,
	EventMusicSeedRequest:                ClassLocal,
	EventMusicSwingRequest:               ClassLocal,
	EventNetworkConnect:                  ClassLocal,
	EventNetworkDisconnect:               ClassLocal,
	EventParticipantJoined:               ClassBus,
	EventParticipantDeparted:             ClassBus,
	EventPlayoutLead:                     ClassLocal,
	EventCursorStateSync:                 ClassLocal,
	EventSessionState:                    ClassLocal,
	EventGameResetRequest:                ClassBus,
	EventMetaTelemetryRequest:            ClassLocal,
	EventMetaDebugRequest:                ClassLocal,
	EventMetaHelpRequest:                 ClassLocal,
	EventMetaAboutRequest:                ClassLocal,
	EventMetaStatusMessageRequest:        ClassLocal,
	EventMetaSystemCommandRequest:        ClassShared,
	EventGamePauseRequest:                ClassLocal,
	EventGamePauseChanged:                ClassLocal,
	EventGameSpeedRequest:                ClassLocal,
	EventGameSpeedChanged:                ClassLocal,
	EventGameStepRequest:                 ClassLocal,
	EventCycleDamageMultiplierIncrease:   ClassShared,
	EventCycleDamageMultiplierReset:      ClassShared,
	EventFSMRegionRequest:                ClassShared,
	EventNuggetCollected:                 ClassLocal,
	EventNuggetDestroyed:                 ClassLocal,
	EventNuggetJumpRequest:               ClassLocal,
	EventCleanerDirectionalRequest:       ClassLocal,
	EventCleanerSweepingRequest:          ClassLocal,
	EventGoldSpawnRequest:                ClassShared,
	EventGoldSpawnFailed:                 ClassShared,
	EventGoldSpawned:                     ClassShared,
	EventGoldCompleted:                   ClassShared,
	EventGoldTimeout:                     ClassShared,
	EventGoldDestroyed:                   ClassShared,
	EventGoldCancel:                      ClassShared,
	EventGoldJumpRequest:                 ClassBus,
	EventSplashTimerRequest:              ClassLocal,
	EventSplashTimerCancel:               ClassLocal,
	EventEnergyAddRequest:                ClassLocal,
	EventEnergySetRequest:                ClassLocal,
	EventEnergyCrossedZero:               ClassLocal,
	EventEnergyGlyphConsumed:             ClassLocal,
	EventEnergyBlinkStart:                ClassLocal,
	EventEnergyBlinkStop:                 ClassLocal,
	EventShieldActivate:                  ClassLocal,
	EventShieldDeactivate:                ClassLocal,
	EventShieldDrainRequest:              ClassLocal,
	EventWeaponAddRequest:                ClassLocal,
	EventWeaponFireRequest:               ClassLocal,
	EventFireSpecialRequest:              ClassLocal,
	EventMountRequest:                    ClassShared,
	EventHeatAddRequest:                  ClassLocal,
	EventHeatSetRequest:                  ClassLocal,
	EventHeatSpendRequest:                ClassLocal,
	EventHeatBurst:                       ClassLocal,
	EventBoostActivate:                   ClassLocal,
	EventBoostDeactivate:                 ClassLocal,
	EventBoostExtend:                     ClassLocal,
	EventBoostReward:                     ClassLocal,
	EventCharacterTyped:                  ClassLocal,
	EventDeleteRequest:                   ClassLocal,
	EventPingGridRequest:                 ClassLocal,
	EventMaterializeRequest:              ClassStamped,
	EventMaterializeComplete:             ClassStamped,
	EventMaterializeAreaRequest:          ClassStamped,
	EventFlashSpawnOneRequest:            ClassLocal,
	EventFlashSpawnBatchRequest:          ClassLocal,
	EventExplosionRequest:                ClassBus,
	EventExplosionBatchRequest:           ClassBus,
	EventExplosionVisualRequest:          ClassLocal,
	EventExplosionVisualBatchRequest:     ClassLocal,
	EventPulseVisualRequest:              ClassLocal,
	EventDustSpawnOneRequest:             ClassLocal,
	EventDustSpawnBatchRequest:           ClassLocal,
	EventDustAllRequest:                  ClassLocal,
	EventParticleSpawnOne:                ClassLocal,
	EventParticleSpawnBatch:              ClassLocal,
	EventParticleWave:                    ClassLocal,
	EventDeathBatch:                      ClassStamped,
	EventTimerStart:                      ClassStamped,
	EventCompositeMemberDestroyed:        ClassBus,
	EventCompositeIntegrityBreach:        ClassShared,
	EventCompositeDestroyRequest:         ClassShared,
	EventCursorSpawnRequest:              ClassShared,
	EventCursorSpawned:                   ClassShared,
	EventCursorSpawnFailed:               ClassShared,
	EventCursorArmRequest:                ClassLocal,
	EventCursorDespawnRequest:            ClassShared,
	EventCursorDespawned:                 ClassShared,
	EventCursorMoveRequest:               ClassBus,
	EventCursorMoved:                     ClassShared,
	EventCursorPredicted:                 ClassLocal,
	EventCursorDefeatState:               ClassBus,
	EventCursorSetLocalRequest:           ClassLocal,
	EventCursorLocalChanged:              ClassLocal,
	EventSpeciesCreated:                  ClassStamped,
	EventSpeciesKilled:                   ClassStamped,
	EventSpeciesKillConfirmed:            ClassLocal,
	EventDrainDefeated:                   ClassBus,
	EventFuseQuasarRequest:               ClassLocal,
	EventFuseSwarmRequest:                ClassLocal,
	EventDrainPause:                      ClassLocal,
	EventDrainResume:                     ClassLocal,
	EventQuasarSpawnRequest:              ClassBus,
	EventQuasarCancelRequest:             ClassShared,
	EventSwarmSpawnRequest:               ClassBus,
	EventSwarmCancelRequest:              ClassShared,
	EventStormSpawnRequest:               ClassShared,
	EventStormCancelRequest:              ClassShared,
	EventKrakenSpawnRequest:              ClassShared,
	EventKrakenSpawnFailed:               ClassShared,
	EventKrakenCancelRequest:             ClassShared,
	EventWindStart:                       ClassShared,
	EventWindCancel:                      ClassShared,
	EventGrayoutStart:                    ClassLocal,
	EventGrayoutEnd:                      ClassLocal,
	EventStrobeRequest:                   ClassLocal,
	EventSpiritSpawnRequest:              ClassStamped,
	EventSpiritDespawnRequest:            ClassStamped,
	EventLightningSpawnRequest:           ClassLocal,
	EventLightningUpdateRequest:          ClassLocal,
	EventLightningDespawnRequest:         ClassLocal,
	EventCombatAttackDirectRequest:       ClassStamped,
	EventCombatAttackAreaRequest:         ClassLocal,
	EventCombatAttackAreaCrossingRequest: ClassBus,
	EventCombatHealRequest:               ClassBus,
	EventLootSpawnRequest:                ClassLocal,
	EventMissileSpawnRequest:             ClassLocal,
	EventBulletSpawnRequest:              ClassLocal,
	EventMarkerSpawnRequest:              ClassShared,
	EventMotionMarkerShowColored:         ClassLocal,
	EventMotionMarkerClearColored:        ClassLocal,
	EventModeChanged:                     ClassLocal,
	EventWallSpawnRequest:                ClassShared,
	EventWallBatchSpawnRequest:           ClassShared,
	EventWallCompositeSpawnRequest:       ClassShared,
	EventWallPatternSpawnRequest:         ClassShared,
	EventMazeSpawnRequest:                ClassShared,
	EventWallDespawnRequest:              ClassShared,
	EventWallMaskChangeRequest:           ClassShared,
	EventWallPushCheckRequest:            ClassShared,
	EventWallSpawned:                     ClassShared,
	EventWallDespawned:                   ClassShared,
	EventWallDespawnAll:                  ClassShared,
	EventFadeoutSpawnOne:                 ClassLocal,
	EventFadeoutSpawnBatch:               ClassLocal,
	EventPylonSpawnRequest:               ClassShared,
	EventPylonSpawnFailed:                ClassShared,
	EventPylonCancelRequest:              ClassShared,
	EventSnakeSpawnRequest:               ClassShared,
	EventSnakeCancelRequest:              ClassShared,
	EventTargetGroupUpdate:               ClassShared,
	EventTargetGroupRemove:               ClassShared,
	EventNavigationRegraph:               ClassShared,
	EventRouteGraphRequest:               ClassShared,
	EventRouteGraphComputed:              ClassShared,
	EventEyeSpawnRequest:                 ClassShared,
	EventEyeCancelRequest:                ClassShared,
	EventTowerSpawnRequest:               ClassShared,
	EventTowerSpawnFailed:                ClassShared,
	EventTowerCancelRequest:              ClassShared,
	EventGatewaySpawnRequest:             ClassShared,
	EventGatewayDespawnRequest:           ClassShared,
	EventGatewayDespawned:                ClassShared,
	EventGeneticRegisterSpecies:          ClassShared,
	EventGeneticAbandonEval:              ClassShared,
	EventDebugFlowToggle:                 ClassLocal,
	EventDebugGraphToggle:                ClassLocal,
}
